// Generated by @kevinmichaelchen/distilled. Do not edit by hand.
import * as S from "@kevinmichaelchen/distilled/schema";
import * as API from "@kevinmichaelchen/distilled/api";
import * as T from "../traits.ts";
import * as Retry from "../retry.ts";
import { TmdbProtocol, type TmdbOpError, type TmdbOpContext } from "../protocol.ts";

// Input Schema
export interface AccountDetailsInput { account_id: number; session_id?: string }
export const AccountDetailsInput = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    account_id: S.Number.pipe(T.Label("account_id")),
    session_id: S.optional(S.String).pipe(T.Query("session_id")),
  }).pipe(T.Http({ method: "GET", uri: "/3/account/{account_id}", code: 200 }))
).annotate({ identifier: "AccountDetailsInput" }) as unknown as S.Codec<AccountDetailsInput>;

// Output Schema
export interface AccountDetailsOutput { avatar?: { gravatar?: { hash?: string }; tmdb?: { avatar_path?: string } }; id?: number; iso_639_1?: string; iso_3166_1?: string; name?: string; include_adult?: boolean; username?: string }
export const AccountDetailsOutput = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    avatar: S.optional(S.Struct({
      gravatar: S.optional(S.Struct({
        hash: S.optional(S.String),
      })),
      tmdb: S.optional(S.Struct({
        avatar_path: S.optional(S.String),
      })),
    })),
    id: S.optional(S.Number),
    iso_639_1: S.optional(S.String),
    iso_3166_1: S.optional(S.String),
    name: S.optional(S.String),
    include_adult: S.optional(S.Boolean),
    username: S.optional(S.String),
  })
).annotate({ identifier: "AccountDetailsOutput" }) as unknown as S.Codec<AccountDetailsOutput>;

// The operation
/**
 * Details
 *
 * Get the public details of an account on TMDB.
 */
export type AccountDetailsError = TmdbOpError;
export const accountDetails: API.OperationMethod<
  AccountDetailsInput,
  AccountDetailsOutput,
  AccountDetailsError,
  TmdbOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: AccountDetailsInput,
  output: AccountDetailsOutput,
  errors: [] as const,
  protocol: TmdbProtocol,
  retry: Retry.Retry,
}));

// Input Schema
export interface AccountAddFavoriteInput { account_id: number; session_id?: string; body?: { RAW_BODY: string } }
export const AccountAddFavoriteInput = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    account_id: S.Number.pipe(T.Label("account_id")),
    session_id: S.optional(S.String).pipe(T.Query("session_id")),
    body: S.optional(S.Struct({
      RAW_BODY: S.String,
    }).pipe(T.HttpBody())),
  }).pipe(T.Http({ method: "POST", uri: "/3/account/{account_id}/favorite", code: 200 }))
).annotate({ identifier: "AccountAddFavoriteInput" }) as unknown as S.Codec<AccountAddFavoriteInput>;

// Output Schema
export interface AccountAddFavoriteOutput { status_code?: number; status_message?: string }
export const AccountAddFavoriteOutput = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    status_code: S.optional(S.Number),
    status_message: S.optional(S.String),
  })
).annotate({ identifier: "AccountAddFavoriteOutput" }) as unknown as S.Codec<AccountAddFavoriteOutput>;

// The operation
/**
 * Add Favorite
 *
 * Mark a movie or TV show as a favourite.
 */
export type AccountAddFavoriteError = TmdbOpError;
export const accountAddFavorite: API.OperationMethod<
  AccountAddFavoriteInput,
  AccountAddFavoriteOutput,
  AccountAddFavoriteError,
  TmdbOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: AccountAddFavoriteInput,
  output: AccountAddFavoriteOutput,
  errors: [] as const,
  protocol: TmdbProtocol,
}));

// Input Schema
export interface AccountAddToWatchlistInput { account_id: number; session_id?: string; body?: { RAW_BODY: string } }
export const AccountAddToWatchlistInput = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    account_id: S.Number.pipe(T.Label("account_id")),
    session_id: S.optional(S.String).pipe(T.Query("session_id")),
    body: S.optional(S.Struct({
      RAW_BODY: S.String,
    }).pipe(T.HttpBody())),
  }).pipe(T.Http({ method: "POST", uri: "/3/account/{account_id}/watchlist", code: 200 }))
).annotate({ identifier: "AccountAddToWatchlistInput" }) as unknown as S.Codec<AccountAddToWatchlistInput>;

// Output Schema
export interface AccountAddToWatchlistOutput { status_code?: number; status_message?: string }
export const AccountAddToWatchlistOutput = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    status_code: S.optional(S.Number),
    status_message: S.optional(S.String),
  })
).annotate({ identifier: "AccountAddToWatchlistOutput" }) as unknown as S.Codec<AccountAddToWatchlistOutput>;

// The operation
/**
 * Add To Watchlist
 *
 * Add a movie or TV show to your watchlist.
 */
export type AccountAddToWatchlistError = TmdbOpError;
export const accountAddToWatchlist: API.OperationMethod<
  AccountAddToWatchlistInput,
  AccountAddToWatchlistOutput,
  AccountAddToWatchlistError,
  TmdbOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: AccountAddToWatchlistInput,
  output: AccountAddToWatchlistOutput,
  errors: [] as const,
  protocol: TmdbProtocol,
}));

// Input Schema
export interface AccountGetFavoritesInput { account_id: number; language?: string; page?: number; session_id?: string; sort_by?: "created_at.asc" | "created_at.desc" }
export const AccountGetFavoritesInput = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    account_id: S.Number.pipe(T.Label("account_id")),
    language: S.optional(S.String).pipe(T.Query("language")),
    page: S.optional(S.Number).pipe(T.Query("page")),
    session_id: S.optional(S.String).pipe(T.Query("session_id")),
    sort_by: S.optional(S.Literals(["created_at.asc", "created_at.desc"])).pipe(T.Query("sort_by")),
  }).pipe(T.Http({ method: "GET", uri: "/3/account/{account_id}/favorite/movies", code: 200 }))
).annotate({ identifier: "AccountGetFavoritesInput" }) as unknown as S.Codec<AccountGetFavoritesInput>;

// Output Schema
export interface AccountGetFavoritesOutput { page?: number; results?: ReadonlyArray<{ adult?: boolean; backdrop_path?: string; genre_ids?: ReadonlyArray<number>; id?: number; original_language?: string; original_title?: string; overview?: string; popularity?: number; poster_path?: string; release_date?: string; title?: string; video?: boolean; vote_average?: number; vote_count?: number }>; total_pages?: number; total_results?: number }
export const AccountGetFavoritesOutput = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    page: S.optional(S.Number),
    results: S.optional(S.Array(S.Struct({
      adult: S.optional(S.Boolean),
      backdrop_path: S.optional(S.String),
      genre_ids: S.optional(S.Array(S.Number)),
      id: S.optional(S.Number),
      original_language: S.optional(S.String),
      original_title: S.optional(S.String),
      overview: S.optional(S.String),
      popularity: S.optional(S.Number),
      poster_path: S.optional(S.String),
      release_date: S.optional(S.String),
      title: S.optional(S.String),
      video: S.optional(S.Boolean),
      vote_average: S.optional(S.Number),
      vote_count: S.optional(S.Number),
    }))),
    total_pages: S.optional(S.Number),
    total_results: S.optional(S.Number),
  })
).annotate({ identifier: "AccountGetFavoritesOutput" }) as unknown as S.Codec<AccountGetFavoritesOutput>;

// The operation
/**
 * Favorite Movies
 *
 * Get a users list of favourite movies.
 */
export type AccountGetFavoritesError = TmdbOpError;
export const accountGetFavorites: API.OperationMethod<
  AccountGetFavoritesInput,
  AccountGetFavoritesOutput,
  AccountGetFavoritesError,
  TmdbOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: AccountGetFavoritesInput,
  output: AccountGetFavoritesOutput,
  errors: [] as const,
  protocol: TmdbProtocol,
  retry: Retry.Retry,
}));

// Input Schema
export interface AccountFavoriteTvInput { account_id: number; language?: string; page?: number; session_id?: string; sort_by?: "created_at.asc" | "created_at.desc" }
export const AccountFavoriteTvInput = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    account_id: S.Number.pipe(T.Label("account_id")),
    language: S.optional(S.String).pipe(T.Query("language")),
    page: S.optional(S.Number).pipe(T.Query("page")),
    session_id: S.optional(S.String).pipe(T.Query("session_id")),
    sort_by: S.optional(S.Literals(["created_at.asc", "created_at.desc"])).pipe(T.Query("sort_by")),
  }).pipe(T.Http({ method: "GET", uri: "/3/account/{account_id}/favorite/tv", code: 200 }))
).annotate({ identifier: "AccountFavoriteTvInput" }) as unknown as S.Codec<AccountFavoriteTvInput>;

// Output Schema
export interface AccountFavoriteTvOutput { page?: number; results?: ReadonlyArray<{ adult?: boolean; backdrop_path?: string; genre_ids?: ReadonlyArray<number>; id?: number; origin_country?: ReadonlyArray<string>; original_language?: string; original_name?: string; overview?: string; popularity?: number; poster_path?: string; first_air_date?: string; name?: string; vote_average?: number; vote_count?: number }>; total_pages?: number; total_results?: number }
export const AccountFavoriteTvOutput = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    page: S.optional(S.Number),
    results: S.optional(S.Array(S.Struct({
      adult: S.optional(S.Boolean),
      backdrop_path: S.optional(S.String),
      genre_ids: S.optional(S.Array(S.Number)),
      id: S.optional(S.Number),
      origin_country: S.optional(S.Array(S.String)),
      original_language: S.optional(S.String),
      original_name: S.optional(S.String),
      overview: S.optional(S.String),
      popularity: S.optional(S.Number),
      poster_path: S.optional(S.String),
      first_air_date: S.optional(S.String),
      name: S.optional(S.String),
      vote_average: S.optional(S.Number),
      vote_count: S.optional(S.Number),
    }))),
    total_pages: S.optional(S.Number),
    total_results: S.optional(S.Number),
  })
).annotate({ identifier: "AccountFavoriteTvOutput" }) as unknown as S.Codec<AccountFavoriteTvOutput>;

// The operation
/**
 * Favorite TV
 *
 * Get a users list of favourite TV shows.
 */
export type AccountFavoriteTvError = TmdbOpError;
export const accountFavoriteTv: API.OperationMethod<
  AccountFavoriteTvInput,
  AccountFavoriteTvOutput,
  AccountFavoriteTvError,
  TmdbOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: AccountFavoriteTvInput,
  output: AccountFavoriteTvOutput,
  errors: [] as const,
  protocol: TmdbProtocol,
  retry: Retry.Retry,
}));

// Input Schema
export interface AccountListsInput { account_id: number; page?: number; session_id?: string }
export const AccountListsInput = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    account_id: S.Number.pipe(T.Label("account_id")),
    page: S.optional(S.Number).pipe(T.Query("page")),
    session_id: S.optional(S.String).pipe(T.Query("session_id")),
  }).pipe(T.Http({ method: "GET", uri: "/3/account/{account_id}/lists", code: 200 }))
).annotate({ identifier: "AccountListsInput" }) as unknown as S.Codec<AccountListsInput>;

// Output Schema
export interface AccountListsOutput { page?: number; results?: ReadonlyArray<{ description?: string; favorite_count?: number; id?: number; item_count?: number; iso_639_1?: string; list_type?: string; name?: string; poster_path?: unknown }>; total_pages?: number; total_results?: number }
export const AccountListsOutput = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    page: S.optional(S.Number),
    results: S.optional(S.Array(S.Struct({
      description: S.optional(S.String),
      favorite_count: S.optional(S.Number),
      id: S.optional(S.Number),
      item_count: S.optional(S.Number),
      iso_639_1: S.optional(S.String),
      list_type: S.optional(S.String),
      name: S.optional(S.String),
      poster_path: S.optional(S.Unknown),
    }))),
    total_pages: S.optional(S.Number),
    total_results: S.optional(S.Number),
  })
).annotate({ identifier: "AccountListsOutput" }) as unknown as S.Codec<AccountListsOutput>;

// The operation
/**
 * Lists
 *
 * Get a users list of custom lists.
 */
export type AccountListsError = TmdbOpError;
export const accountLists: API.OperationMethod<
  AccountListsInput,
  AccountListsOutput,
  AccountListsError,
  TmdbOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: AccountListsInput,
  output: AccountListsOutput,
  errors: [] as const,
  protocol: TmdbProtocol,
  retry: Retry.Retry,
}));

// Input Schema
export interface AccountRatedMoviesInput { account_id: number; language?: string; page?: number; session_id?: string; sort_by?: "created_at.asc" | "created_at.desc" }
export const AccountRatedMoviesInput = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    account_id: S.Number.pipe(T.Label("account_id")),
    language: S.optional(S.String).pipe(T.Query("language")),
    page: S.optional(S.Number).pipe(T.Query("page")),
    session_id: S.optional(S.String).pipe(T.Query("session_id")),
    sort_by: S.optional(S.Literals(["created_at.asc", "created_at.desc"])).pipe(T.Query("sort_by")),
  }).pipe(T.Http({ method: "GET", uri: "/3/account/{account_id}/rated/movies", code: 200 }))
).annotate({ identifier: "AccountRatedMoviesInput" }) as unknown as S.Codec<AccountRatedMoviesInput>;

// Output Schema
export interface AccountRatedMoviesOutput { page?: number; results?: ReadonlyArray<{ adult?: boolean; backdrop_path?: string; genre_ids?: ReadonlyArray<number>; id?: number; original_language?: string; original_title?: string; overview?: string; popularity?: number; poster_path?: string; release_date?: string; title?: string; video?: boolean; vote_average?: number; vote_count?: number; rating?: number }>; total_pages?: number; total_results?: number }
export const AccountRatedMoviesOutput = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    page: S.optional(S.Number),
    results: S.optional(S.Array(S.Struct({
      adult: S.optional(S.Boolean),
      backdrop_path: S.optional(S.String),
      genre_ids: S.optional(S.Array(S.Number)),
      id: S.optional(S.Number),
      original_language: S.optional(S.String),
      original_title: S.optional(S.String),
      overview: S.optional(S.String),
      popularity: S.optional(S.Number),
      poster_path: S.optional(S.String),
      release_date: S.optional(S.String),
      title: S.optional(S.String),
      video: S.optional(S.Boolean),
      vote_average: S.optional(S.Number),
      vote_count: S.optional(S.Number),
      rating: S.optional(S.Number),
    }))),
    total_pages: S.optional(S.Number),
    total_results: S.optional(S.Number),
  })
).annotate({ identifier: "AccountRatedMoviesOutput" }) as unknown as S.Codec<AccountRatedMoviesOutput>;

// The operation
/**
 * Rated Movies
 *
 * Get a users list of rated movies.
 */
export type AccountRatedMoviesError = TmdbOpError;
export const accountRatedMovies: API.OperationMethod<
  AccountRatedMoviesInput,
  AccountRatedMoviesOutput,
  AccountRatedMoviesError,
  TmdbOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: AccountRatedMoviesInput,
  output: AccountRatedMoviesOutput,
  errors: [] as const,
  protocol: TmdbProtocol,
  retry: Retry.Retry,
}));

// Input Schema
export interface AccountRatedTvInput { account_id: number; language?: string; page?: number; session_id?: string; sort_by?: "created_at.asc" | "created_at.desc" }
export const AccountRatedTvInput = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    account_id: S.Number.pipe(T.Label("account_id")),
    language: S.optional(S.String).pipe(T.Query("language")),
    page: S.optional(S.Number).pipe(T.Query("page")),
    session_id: S.optional(S.String).pipe(T.Query("session_id")),
    sort_by: S.optional(S.Literals(["created_at.asc", "created_at.desc"])).pipe(T.Query("sort_by")),
  }).pipe(T.Http({ method: "GET", uri: "/3/account/{account_id}/rated/tv", code: 200 }))
).annotate({ identifier: "AccountRatedTvInput" }) as unknown as S.Codec<AccountRatedTvInput>;

// Output Schema
export interface AccountRatedTvOutput { page?: number; results?: ReadonlyArray<{ adult?: boolean; backdrop_path?: string; genre_ids?: ReadonlyArray<number>; id?: number; origin_country?: ReadonlyArray<string>; original_language?: string; original_name?: string; overview?: string; popularity?: number; poster_path?: string; first_air_date?: string; name?: string; vote_average?: number; vote_count?: number; rating?: number }>; total_pages?: number; total_results?: number }
export const AccountRatedTvOutput = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    page: S.optional(S.Number),
    results: S.optional(S.Array(S.Struct({
      adult: S.optional(S.Boolean),
      backdrop_path: S.optional(S.String),
      genre_ids: S.optional(S.Array(S.Number)),
      id: S.optional(S.Number),
      origin_country: S.optional(S.Array(S.String)),
      original_language: S.optional(S.String),
      original_name: S.optional(S.String),
      overview: S.optional(S.String),
      popularity: S.optional(S.Number),
      poster_path: S.optional(S.String),
      first_air_date: S.optional(S.String),
      name: S.optional(S.String),
      vote_average: S.optional(S.Number),
      vote_count: S.optional(S.Number),
      rating: S.optional(S.Number),
    }))),
    total_pages: S.optional(S.Number),
    total_results: S.optional(S.Number),
  })
).annotate({ identifier: "AccountRatedTvOutput" }) as unknown as S.Codec<AccountRatedTvOutput>;

// The operation
/**
 * Rated TV
 *
 * Get a users list of rated TV shows.
 */
export type AccountRatedTvError = TmdbOpError;
export const accountRatedTv: API.OperationMethod<
  AccountRatedTvInput,
  AccountRatedTvOutput,
  AccountRatedTvError,
  TmdbOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: AccountRatedTvInput,
  output: AccountRatedTvOutput,
  errors: [] as const,
  protocol: TmdbProtocol,
  retry: Retry.Retry,
}));

// Input Schema
export interface AccountRatedTvEpisodesInput { account_id: number; language?: string; page?: number; session_id?: string; sort_by?: "created_at.asc" | "created_at.desc" }
export const AccountRatedTvEpisodesInput = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    account_id: S.Number.pipe(T.Label("account_id")),
    language: S.optional(S.String).pipe(T.Query("language")),
    page: S.optional(S.Number).pipe(T.Query("page")),
    session_id: S.optional(S.String).pipe(T.Query("session_id")),
    sort_by: S.optional(S.Literals(["created_at.asc", "created_at.desc"])).pipe(T.Query("sort_by")),
  }).pipe(T.Http({ method: "GET", uri: "/3/account/{account_id}/rated/tv/episodes", code: 200 }))
).annotate({ identifier: "AccountRatedTvEpisodesInput" }) as unknown as S.Codec<AccountRatedTvEpisodesInput>;

// Output Schema
export interface AccountRatedTvEpisodesOutput { page?: number; results?: ReadonlyArray<{ air_date?: string; episode_number?: number; id?: number; name?: string; overview?: string; production_code?: string; runtime?: number; season_number?: number; show_id?: number; still_path?: string; vote_average?: number; vote_count?: number; rating?: number }>; total_pages?: number; total_results?: number }
export const AccountRatedTvEpisodesOutput = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    page: S.optional(S.Number),
    results: S.optional(S.Array(S.Struct({
      air_date: S.optional(S.String),
      episode_number: S.optional(S.Number),
      id: S.optional(S.Number),
      name: S.optional(S.String),
      overview: S.optional(S.String),
      production_code: S.optional(S.String),
      runtime: S.optional(S.Number),
      season_number: S.optional(S.Number),
      show_id: S.optional(S.Number),
      still_path: S.optional(S.String),
      vote_average: S.optional(S.Number),
      vote_count: S.optional(S.Number),
      rating: S.optional(S.Number),
    }))),
    total_pages: S.optional(S.Number),
    total_results: S.optional(S.Number),
  })
).annotate({ identifier: "AccountRatedTvEpisodesOutput" }) as unknown as S.Codec<AccountRatedTvEpisodesOutput>;

// The operation
/**
 * Rated TV Episodes
 *
 * Get a users list of rated TV episodes.
 */
export type AccountRatedTvEpisodesError = TmdbOpError;
export const accountRatedTvEpisodes: API.OperationMethod<
  AccountRatedTvEpisodesInput,
  AccountRatedTvEpisodesOutput,
  AccountRatedTvEpisodesError,
  TmdbOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: AccountRatedTvEpisodesInput,
  output: AccountRatedTvEpisodesOutput,
  errors: [] as const,
  protocol: TmdbProtocol,
  retry: Retry.Retry,
}));

// Input Schema
export interface AccountWatchlistMoviesInput { account_id: number; language?: string; page?: number; session_id?: string; sort_by?: "created_at.asc" | "created_at.desc" }
export const AccountWatchlistMoviesInput = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    account_id: S.Number.pipe(T.Label("account_id")),
    language: S.optional(S.String).pipe(T.Query("language")),
    page: S.optional(S.Number).pipe(T.Query("page")),
    session_id: S.optional(S.String).pipe(T.Query("session_id")),
    sort_by: S.optional(S.Literals(["created_at.asc", "created_at.desc"])).pipe(T.Query("sort_by")),
  }).pipe(T.Http({ method: "GET", uri: "/3/account/{account_id}/watchlist/movies", code: 200 }))
).annotate({ identifier: "AccountWatchlistMoviesInput" }) as unknown as S.Codec<AccountWatchlistMoviesInput>;

// Output Schema
export interface AccountWatchlistMoviesOutput { page?: number; results?: ReadonlyArray<{ adult?: boolean; backdrop_path?: string; genre_ids?: ReadonlyArray<number>; id?: number; original_language?: string; original_title?: string; overview?: string; popularity?: number; poster_path?: string; release_date?: string; title?: string; video?: boolean; vote_average?: number; vote_count?: number }>; total_pages?: number; total_results?: number }
export const AccountWatchlistMoviesOutput = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    page: S.optional(S.Number),
    results: S.optional(S.Array(S.Struct({
      adult: S.optional(S.Boolean),
      backdrop_path: S.optional(S.String),
      genre_ids: S.optional(S.Array(S.Number)),
      id: S.optional(S.Number),
      original_language: S.optional(S.String),
      original_title: S.optional(S.String),
      overview: S.optional(S.String),
      popularity: S.optional(S.Number),
      poster_path: S.optional(S.String),
      release_date: S.optional(S.String),
      title: S.optional(S.String),
      video: S.optional(S.Boolean),
      vote_average: S.optional(S.Number),
      vote_count: S.optional(S.Number),
    }))),
    total_pages: S.optional(S.Number),
    total_results: S.optional(S.Number),
  })
).annotate({ identifier: "AccountWatchlistMoviesOutput" }) as unknown as S.Codec<AccountWatchlistMoviesOutput>;

// The operation
/**
 * Watchlist Movies
 *
 * Get a list of movies added to a users watchlist.
 */
export type AccountWatchlistMoviesError = TmdbOpError;
export const accountWatchlistMovies: API.OperationMethod<
  AccountWatchlistMoviesInput,
  AccountWatchlistMoviesOutput,
  AccountWatchlistMoviesError,
  TmdbOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: AccountWatchlistMoviesInput,
  output: AccountWatchlistMoviesOutput,
  errors: [] as const,
  protocol: TmdbProtocol,
  retry: Retry.Retry,
}));

// Input Schema
export interface AccountWatchlistTvInput { account_id: number; language?: string; page?: number; session_id?: string; sort_by?: "created_at.asc" | "created_at.desc" }
export const AccountWatchlistTvInput = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    account_id: S.Number.pipe(T.Label("account_id")),
    language: S.optional(S.String).pipe(T.Query("language")),
    page: S.optional(S.Number).pipe(T.Query("page")),
    session_id: S.optional(S.String).pipe(T.Query("session_id")),
    sort_by: S.optional(S.Literals(["created_at.asc", "created_at.desc"])).pipe(T.Query("sort_by")),
  }).pipe(T.Http({ method: "GET", uri: "/3/account/{account_id}/watchlist/tv", code: 200 }))
).annotate({ identifier: "AccountWatchlistTvInput" }) as unknown as S.Codec<AccountWatchlistTvInput>;

// Output Schema
export interface AccountWatchlistTvOutput { page?: number; results?: ReadonlyArray<{ adult?: boolean; backdrop_path?: string; genre_ids?: ReadonlyArray<number>; id?: number; origin_country?: ReadonlyArray<string>; original_language?: string; original_name?: string; overview?: string; popularity?: number; poster_path?: string; first_air_date?: string; name?: string; vote_average?: number; vote_count?: number }>; total_pages?: number; total_results?: number }
export const AccountWatchlistTvOutput = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    page: S.optional(S.Number),
    results: S.optional(S.Array(S.Struct({
      adult: S.optional(S.Boolean),
      backdrop_path: S.optional(S.String),
      genre_ids: S.optional(S.Array(S.Number)),
      id: S.optional(S.Number),
      origin_country: S.optional(S.Array(S.String)),
      original_language: S.optional(S.String),
      original_name: S.optional(S.String),
      overview: S.optional(S.String),
      popularity: S.optional(S.Number),
      poster_path: S.optional(S.String),
      first_air_date: S.optional(S.String),
      name: S.optional(S.String),
      vote_average: S.optional(S.Number),
      vote_count: S.optional(S.Number),
    }))),
    total_pages: S.optional(S.Number),
    total_results: S.optional(S.Number),
  })
).annotate({ identifier: "AccountWatchlistTvOutput" }) as unknown as S.Codec<AccountWatchlistTvOutput>;

// The operation
/**
 * Watchlist TV
 *
 * Get a list of TV shows added to a users watchlist.
 */
export type AccountWatchlistTvError = TmdbOpError;
export const accountWatchlistTv: API.OperationMethod<
  AccountWatchlistTvInput,
  AccountWatchlistTvOutput,
  AccountWatchlistTvError,
  TmdbOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: AccountWatchlistTvInput,
  output: AccountWatchlistTvOutput,
  errors: [] as const,
  protocol: TmdbProtocol,
  retry: Retry.Retry,
}));
