// Generated by @kevinmichaelchen/distilled. Do not edit by hand.
import * as S from "@kevinmichaelchen/distilled/schema";
import * as API from "@kevinmichaelchen/distilled/api";
import * as T from "../traits.ts";
import * as Retry from "../retry.ts";
import { TmdbProtocol, type TmdbOpError, type TmdbOpContext } from "../protocol.ts";

// Input Schema
export interface AuthenticationValidateKeyInput {  }
export const AuthenticationValidateKeyInput = /*@__PURE__*/ S.suspend(() =>
  S.Struct({

  }).pipe(T.Http({ method: "GET", uri: "/3/authentication", code: 200 }))
).annotate({ identifier: "AuthenticationValidateKeyInput" }) as unknown as S.Codec<AuthenticationValidateKeyInput>;

// Output Schema
export interface AuthenticationValidateKeyOutput { success?: boolean; status_code?: number; status_message?: string }
export const AuthenticationValidateKeyOutput = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    success: S.optional(S.Boolean),
    status_code: S.optional(S.Number),
    status_message: S.optional(S.String),
  })
).annotate({ identifier: "AuthenticationValidateKeyOutput" }) as unknown as S.Codec<AuthenticationValidateKeyOutput>;

// The operation
/**
 * Validate Key
 *
 * Test your API Key to see if it's valid.
 */
export type AuthenticationValidateKeyError = TmdbOpError;
export const authenticationValidateKey: API.OperationMethod<
  AuthenticationValidateKeyInput,
  AuthenticationValidateKeyOutput,
  AuthenticationValidateKeyError,
  TmdbOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: AuthenticationValidateKeyInput,
  output: AuthenticationValidateKeyOutput,
  errors: [] as const,
  protocol: TmdbProtocol,
  retry: Retry.Retry,
}));

// Input Schema
export interface AuthenticationCreateGuestSessionInput {  }
export const AuthenticationCreateGuestSessionInput = /*@__PURE__*/ S.suspend(() =>
  S.Struct({

  }).pipe(T.Http({ method: "GET", uri: "/3/authentication/guest_session/new", code: 200 }))
).annotate({ identifier: "AuthenticationCreateGuestSessionInput" }) as unknown as S.Codec<AuthenticationCreateGuestSessionInput>;

// Output Schema
export interface AuthenticationCreateGuestSessionOutput { success?: boolean; guest_session_id?: string; expires_at?: string }
export const AuthenticationCreateGuestSessionOutput = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    success: S.optional(S.Boolean),
    guest_session_id: S.optional(S.String),
    expires_at: S.optional(S.String),
  })
).annotate({ identifier: "AuthenticationCreateGuestSessionOutput" }) as unknown as S.Codec<AuthenticationCreateGuestSessionOutput>;

// The operation
/**
 * Create Guest Session
 */
export type AuthenticationCreateGuestSessionError = TmdbOpError;
export const authenticationCreateGuestSession: API.OperationMethod<
  AuthenticationCreateGuestSessionInput,
  AuthenticationCreateGuestSessionOutput,
  AuthenticationCreateGuestSessionError,
  TmdbOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: AuthenticationCreateGuestSessionInput,
  output: AuthenticationCreateGuestSessionOutput,
  errors: [] as const,
  protocol: TmdbProtocol,
  retry: Retry.Retry,
}));

// Input Schema
export interface AuthenticationCreateRequestTokenInput {  }
export const AuthenticationCreateRequestTokenInput = /*@__PURE__*/ S.suspend(() =>
  S.Struct({

  }).pipe(T.Http({ method: "GET", uri: "/3/authentication/token/new", code: 200 }))
).annotate({ identifier: "AuthenticationCreateRequestTokenInput" }) as unknown as S.Codec<AuthenticationCreateRequestTokenInput>;

// Output Schema
export interface AuthenticationCreateRequestTokenOutput { success?: boolean; expires_at?: string; request_token?: string }
export const AuthenticationCreateRequestTokenOutput = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    success: S.optional(S.Boolean),
    expires_at: S.optional(S.String),
    request_token: S.optional(S.String),
  })
).annotate({ identifier: "AuthenticationCreateRequestTokenOutput" }) as unknown as S.Codec<AuthenticationCreateRequestTokenOutput>;

// The operation
/**
 * Create Request Token
 */
export type AuthenticationCreateRequestTokenError = TmdbOpError;
export const authenticationCreateRequestToken: API.OperationMethod<
  AuthenticationCreateRequestTokenInput,
  AuthenticationCreateRequestTokenOutput,
  AuthenticationCreateRequestTokenError,
  TmdbOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: AuthenticationCreateRequestTokenInput,
  output: AuthenticationCreateRequestTokenOutput,
  errors: [] as const,
  protocol: TmdbProtocol,
  retry: Retry.Retry,
}));

// Input Schema
export interface AuthenticationCreateSessionInput { body?: { RAW_BODY: string } }
export const AuthenticationCreateSessionInput = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    body: S.optional(S.Struct({
      RAW_BODY: S.String,
    }).pipe(T.HttpBody())),
  }).pipe(T.Http({ method: "POST", uri: "/3/authentication/session/new", code: 200 }))
).annotate({ identifier: "AuthenticationCreateSessionInput" }) as unknown as S.Codec<AuthenticationCreateSessionInput>;

// Output Schema
export interface AuthenticationCreateSessionOutput { success?: boolean; session_id?: string }
export const AuthenticationCreateSessionOutput = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    success: S.optional(S.Boolean),
    session_id: S.optional(S.String),
  })
).annotate({ identifier: "AuthenticationCreateSessionOutput" }) as unknown as S.Codec<AuthenticationCreateSessionOutput>;

// The operation
/**
 * Create Session
 */
export type AuthenticationCreateSessionError = TmdbOpError;
export const authenticationCreateSession: API.OperationMethod<
  AuthenticationCreateSessionInput,
  AuthenticationCreateSessionOutput,
  AuthenticationCreateSessionError,
  TmdbOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: AuthenticationCreateSessionInput,
  output: AuthenticationCreateSessionOutput,
  errors: [] as const,
  protocol: TmdbProtocol,
}));

// Input Schema
export interface AuthenticationCreateSessionFromV4TokenInput { body?: { RAW_BODY: string } }
export const AuthenticationCreateSessionFromV4TokenInput = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    body: S.optional(S.Struct({
      RAW_BODY: S.String,
    }).pipe(T.HttpBody())),
  }).pipe(T.Http({ method: "POST", uri: "/3/authentication/session/convert/4", code: 200 }))
).annotate({ identifier: "AuthenticationCreateSessionFromV4TokenInput" }) as unknown as S.Codec<AuthenticationCreateSessionFromV4TokenInput>;

// Output Schema
export interface AuthenticationCreateSessionFromV4TokenOutput { success?: boolean; session_id?: string }
export const AuthenticationCreateSessionFromV4TokenOutput = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    success: S.optional(S.Boolean),
    session_id: S.optional(S.String),
  })
).annotate({ identifier: "AuthenticationCreateSessionFromV4TokenOutput" }) as unknown as S.Codec<AuthenticationCreateSessionFromV4TokenOutput>;

// The operation
/**
 * Create Session (from v4 token)
 */
export type AuthenticationCreateSessionFromV4TokenError = TmdbOpError;
export const authenticationCreateSessionFromV4Token: API.OperationMethod<
  AuthenticationCreateSessionFromV4TokenInput,
  AuthenticationCreateSessionFromV4TokenOutput,
  AuthenticationCreateSessionFromV4TokenError,
  TmdbOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: AuthenticationCreateSessionFromV4TokenInput,
  output: AuthenticationCreateSessionFromV4TokenOutput,
  errors: [] as const,
  protocol: TmdbProtocol,
}));

// Input Schema
export interface AuthenticationCreateSessionFromLoginInput { body?: { RAW_BODY: string } }
export const AuthenticationCreateSessionFromLoginInput = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    body: S.optional(S.Struct({
      RAW_BODY: S.String,
    }).pipe(T.HttpBody())),
  }).pipe(T.Http({ method: "POST", uri: "/3/authentication/token/validate_with_login", code: 200 }))
).annotate({ identifier: "AuthenticationCreateSessionFromLoginInput" }) as unknown as S.Codec<AuthenticationCreateSessionFromLoginInput>;

// Output Schema
export interface AuthenticationCreateSessionFromLoginOutput { success?: boolean; expires_at?: string; request_token?: string }
export const AuthenticationCreateSessionFromLoginOutput = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    success: S.optional(S.Boolean),
    expires_at: S.optional(S.String),
    request_token: S.optional(S.String),
  })
).annotate({ identifier: "AuthenticationCreateSessionFromLoginOutput" }) as unknown as S.Codec<AuthenticationCreateSessionFromLoginOutput>;

// The operation
/**
 * Create Session (with login)
 *
 * This method allows an application to validate a request token by entering a username and password.
 */
export type AuthenticationCreateSessionFromLoginError = TmdbOpError;
export const authenticationCreateSessionFromLogin: API.OperationMethod<
  AuthenticationCreateSessionFromLoginInput,
  AuthenticationCreateSessionFromLoginOutput,
  AuthenticationCreateSessionFromLoginError,
  TmdbOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: AuthenticationCreateSessionFromLoginInput,
  output: AuthenticationCreateSessionFromLoginOutput,
  errors: [] as const,
  protocol: TmdbProtocol,
}));

// Input Schema
export interface AuthenticationDeleteSessionInput { body?: { RAW_BODY: string } }
export const AuthenticationDeleteSessionInput = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    body: S.optional(S.Struct({
      RAW_BODY: S.String,
    }).pipe(T.HttpBody())),
  }).pipe(T.Http({ method: "DELETE", uri: "/3/authentication/session", code: 200 }))
).annotate({ identifier: "AuthenticationDeleteSessionInput" }) as unknown as S.Codec<AuthenticationDeleteSessionInput>;

// Output Schema
export interface AuthenticationDeleteSessionOutput { success?: boolean }
export const AuthenticationDeleteSessionOutput = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    success: S.optional(S.Boolean),
  })
).annotate({ identifier: "AuthenticationDeleteSessionOutput" }) as unknown as S.Codec<AuthenticationDeleteSessionOutput>;

// The operation
/**
 * Delete Session
 */
export type AuthenticationDeleteSessionError = TmdbOpError;
export const authenticationDeleteSession: API.OperationMethod<
  AuthenticationDeleteSessionInput,
  AuthenticationDeleteSessionOutput,
  AuthenticationDeleteSessionError,
  TmdbOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: AuthenticationDeleteSessionInput,
  output: AuthenticationDeleteSessionOutput,
  errors: [] as const,
  protocol: TmdbProtocol,
}));
