// Generated by @kevinmichaelchen/distilled. Do not edit by hand.
import * as S from "@kevinmichaelchen/distilled/schema";
import * as API from "@kevinmichaelchen/distilled/api";
import * as T from "../traits.ts";
import * as Retry from "../retry.ts";
import { TmdbProtocol, type TmdbOpError, type TmdbOpContext } from "../protocol.ts";

// Input Schema
export interface CollectionDetailsInput { collection_id: number; language?: string }
export const CollectionDetailsInput = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    collection_id: S.Number.pipe(T.Label("collection_id")),
    language: S.optional(S.String).pipe(T.Query("language")),
  }).pipe(T.Http({ method: "GET", uri: "/3/collection/{collection_id}", code: 200 }))
).annotate({ identifier: "CollectionDetailsInput" }) as unknown as S.Codec<CollectionDetailsInput>;

// Output Schema
export interface CollectionDetailsOutput { id?: number; name?: string; original_language?: string; original_name?: string; overview?: string; poster_path?: string; backdrop_path?: string; parts?: ReadonlyArray<{ adult?: boolean; backdrop_path?: string; id?: number; name?: string; original_name?: string; overview?: string; poster_path?: string; media_type?: string; original_language?: string; genre_ids?: ReadonlyArray<number>; popularity?: number; release_date?: string; video?: boolean; vote_average?: number; vote_count?: number }> }
export const CollectionDetailsOutput = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.optional(S.Number),
    name: S.optional(S.String),
    original_language: S.optional(S.String),
    original_name: S.optional(S.String),
    overview: S.optional(S.String),
    poster_path: S.optional(S.String),
    backdrop_path: S.optional(S.String),
    parts: S.optional(S.Array(S.Struct({
      adult: S.optional(S.Boolean),
      backdrop_path: S.optional(S.String),
      id: S.optional(S.Number),
      name: S.optional(S.String),
      original_name: S.optional(S.String),
      overview: S.optional(S.String),
      poster_path: S.optional(S.String),
      media_type: S.optional(S.String),
      original_language: S.optional(S.String),
      genre_ids: S.optional(S.Array(S.Number)),
      popularity: S.optional(S.Number),
      release_date: S.optional(S.String),
      video: S.optional(S.Boolean),
      vote_average: S.optional(S.Number),
      vote_count: S.optional(S.Number),
    }))),
  })
).annotate({ identifier: "CollectionDetailsOutput" }) as unknown as S.Codec<CollectionDetailsOutput>;

// The operation
/**
 * Details
 *
 * Get collection details by ID.
 */
export type CollectionDetailsError = TmdbOpError;
export const collectionDetails: API.OperationMethod<
  CollectionDetailsInput,
  CollectionDetailsOutput,
  CollectionDetailsError,
  TmdbOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: CollectionDetailsInput,
  output: CollectionDetailsOutput,
  errors: [] as const,
  protocol: TmdbProtocol,
  retry: Retry.Retry,
}));

// Input Schema
export interface CollectionImagesInput { collection_id: number; include_image_language?: string; language?: string }
export const CollectionImagesInput = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    collection_id: S.Number.pipe(T.Label("collection_id")),
    include_image_language: S.optional(S.String).pipe(T.Query("include_image_language")),
    language: S.optional(S.String).pipe(T.Query("language")),
  }).pipe(T.Http({ method: "GET", uri: "/3/collection/{collection_id}/images", code: 200 }))
).annotate({ identifier: "CollectionImagesInput" }) as unknown as S.Codec<CollectionImagesInput>;

// Output Schema
export interface CollectionImagesOutput { id?: number; backdrops?: ReadonlyArray<{ aspect_ratio?: number; height?: number; iso_639_1?: unknown; file_path?: string; vote_average?: number; vote_count?: number; width?: number }>; posters?: ReadonlyArray<{ aspect_ratio?: number; height?: number; iso_639_1?: string; file_path?: string; vote_average?: number; vote_count?: number; width?: number }> }
export const CollectionImagesOutput = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.optional(S.Number),
    backdrops: S.optional(S.Array(S.Struct({
      aspect_ratio: S.optional(S.Number),
      height: S.optional(S.Number),
      iso_639_1: S.optional(S.Unknown),
      file_path: S.optional(S.String),
      vote_average: S.optional(S.Number),
      vote_count: S.optional(S.Number),
      width: S.optional(S.Number),
    }))),
    posters: S.optional(S.Array(S.Struct({
      aspect_ratio: S.optional(S.Number),
      height: S.optional(S.Number),
      iso_639_1: S.optional(S.String),
      file_path: S.optional(S.String),
      vote_average: S.optional(S.Number),
      vote_count: S.optional(S.Number),
      width: S.optional(S.Number),
    }))),
  })
).annotate({ identifier: "CollectionImagesOutput" }) as unknown as S.Codec<CollectionImagesOutput>;

// The operation
/**
 * Images
 *
 * Get the images that belong to a collection.
 *
 * @param include_image_language - specify a comma separated list of ISO-639-1 values to query, for example: `en-US,null`
 */
export type CollectionImagesError = TmdbOpError;
export const collectionImages: API.OperationMethod<
  CollectionImagesInput,
  CollectionImagesOutput,
  CollectionImagesError,
  TmdbOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: CollectionImagesInput,
  output: CollectionImagesOutput,
  errors: [] as const,
  protocol: TmdbProtocol,
  retry: Retry.Retry,
}));

// Input Schema
export interface CollectionTranslationsInput { collection_id: number }
export const CollectionTranslationsInput = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    collection_id: S.Number.pipe(T.Label("collection_id")),
  }).pipe(T.Http({ method: "GET", uri: "/3/collection/{collection_id}/translations", code: 200 }))
).annotate({ identifier: "CollectionTranslationsInput" }) as unknown as S.Codec<CollectionTranslationsInput>;

// Output Schema
export interface CollectionTranslationsOutput { id?: number; translations?: ReadonlyArray<{ iso_3166_1?: string; iso_639_1?: string; name?: string; english_name?: string; data?: { title?: string; overview?: string; homepage?: string } }> }
export const CollectionTranslationsOutput = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.optional(S.Number),
    translations: S.optional(S.Array(S.Struct({
      iso_3166_1: S.optional(S.String),
      iso_639_1: S.optional(S.String),
      name: S.optional(S.String),
      english_name: S.optional(S.String),
      data: S.optional(S.Struct({
        title: S.optional(S.String),
        overview: S.optional(S.String),
        homepage: S.optional(S.String),
      })),
    }))),
  })
).annotate({ identifier: "CollectionTranslationsOutput" }) as unknown as S.Codec<CollectionTranslationsOutput>;

// The operation
/**
 * Translations
 */
export type CollectionTranslationsError = TmdbOpError;
export const collectionTranslations: API.OperationMethod<
  CollectionTranslationsInput,
  CollectionTranslationsOutput,
  CollectionTranslationsError,
  TmdbOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: CollectionTranslationsInput,
  output: CollectionTranslationsOutput,
  errors: [] as const,
  protocol: TmdbProtocol,
  retry: Retry.Retry,
}));
