// Generated by @kevinmichaelchen/distilled. Do not edit by hand.
import * as S from "@kevinmichaelchen/distilled/schema";
import * as API from "@kevinmichaelchen/distilled/api";
import * as T from "../traits.ts";
import * as Retry from "../retry.ts";
import { TmdbProtocol, type TmdbOpError, type TmdbOpContext } from "../protocol.ts";

// Input Schema
export interface CompanyDetailsInput { company_id: number }
export const CompanyDetailsInput = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    company_id: S.Number.pipe(T.Label("company_id")),
  }).pipe(T.Http({ method: "GET", uri: "/3/company/{company_id}", code: 200 }))
).annotate({ identifier: "CompanyDetailsInput" }) as unknown as S.Codec<CompanyDetailsInput>;

// Output Schema
export interface CompanyDetailsOutput { description?: string; headquarters?: string; homepage?: string; id?: number; logo_path?: string; name?: string; origin_country?: string; parent_company?: unknown }
export const CompanyDetailsOutput = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    description: S.optional(S.String),
    headquarters: S.optional(S.String),
    homepage: S.optional(S.String),
    id: S.optional(S.Number),
    logo_path: S.optional(S.String),
    name: S.optional(S.String),
    origin_country: S.optional(S.String),
    parent_company: S.optional(S.Unknown),
  })
).annotate({ identifier: "CompanyDetailsOutput" }) as unknown as S.Codec<CompanyDetailsOutput>;

// The operation
/**
 * Details
 *
 * Get the company details by ID.
 */
export type CompanyDetailsError = TmdbOpError;
export const companyDetails: API.OperationMethod<
  CompanyDetailsInput,
  CompanyDetailsOutput,
  CompanyDetailsError,
  TmdbOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: CompanyDetailsInput,
  output: CompanyDetailsOutput,
  errors: [] as const,
  protocol: TmdbProtocol,
  retry: Retry.Retry,
}));

// Input Schema
export interface CompanyAlternativeNamesInput { company_id: number }
export const CompanyAlternativeNamesInput = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    company_id: S.Number.pipe(T.Label("company_id")),
  }).pipe(T.Http({ method: "GET", uri: "/3/company/{company_id}/alternative_names", code: 200 }))
).annotate({ identifier: "CompanyAlternativeNamesInput" }) as unknown as S.Codec<CompanyAlternativeNamesInput>;

// Output Schema
export interface CompanyAlternativeNamesOutput { id?: number; results?: ReadonlyArray<{ name?: string; type?: string }> }
export const CompanyAlternativeNamesOutput = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.optional(S.Number),
    results: S.optional(S.Array(S.Struct({
      name: S.optional(S.String),
      type: S.optional(S.String),
    }))),
  })
).annotate({ identifier: "CompanyAlternativeNamesOutput" }) as unknown as S.Codec<CompanyAlternativeNamesOutput>;

// The operation
/**
 * Alternative Names
 *
 * Get the company details by ID.
 */
export type CompanyAlternativeNamesError = TmdbOpError;
export const companyAlternativeNames: API.OperationMethod<
  CompanyAlternativeNamesInput,
  CompanyAlternativeNamesOutput,
  CompanyAlternativeNamesError,
  TmdbOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: CompanyAlternativeNamesInput,
  output: CompanyAlternativeNamesOutput,
  errors: [] as const,
  protocol: TmdbProtocol,
  retry: Retry.Retry,
}));

// Input Schema
export interface CompanyImagesInput { company_id: number }
export const CompanyImagesInput = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    company_id: S.Number.pipe(T.Label("company_id")),
  }).pipe(T.Http({ method: "GET", uri: "/3/company/{company_id}/images", code: 200 }))
).annotate({ identifier: "CompanyImagesInput" }) as unknown as S.Codec<CompanyImagesInput>;

// Output Schema
export interface CompanyImagesOutput { id?: number; logos?: ReadonlyArray<{ aspect_ratio?: number; file_path?: string; height?: number; id?: string; file_type?: string; vote_average?: number; vote_count?: number; width?: number }> }
export const CompanyImagesOutput = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.optional(S.Number),
    logos: S.optional(S.Array(S.Struct({
      aspect_ratio: S.optional(S.Number),
      file_path: S.optional(S.String),
      height: S.optional(S.Number),
      id: S.optional(S.String),
      file_type: S.optional(S.String),
      vote_average: S.optional(S.Number),
      vote_count: S.optional(S.Number),
      width: S.optional(S.Number),
    }))),
  })
).annotate({ identifier: "CompanyImagesOutput" }) as unknown as S.Codec<CompanyImagesOutput>;

// The operation
/**
 * Images
 *
 * Get the company logos by id.
 */
export type CompanyImagesError = TmdbOpError;
export const companyImages: API.OperationMethod<
  CompanyImagesInput,
  CompanyImagesOutput,
  CompanyImagesError,
  TmdbOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: CompanyImagesInput,
  output: CompanyImagesOutput,
  errors: [] as const,
  protocol: TmdbProtocol,
  retry: Retry.Retry,
}));
