// Generated by @kevinmichaelchen/distilled. Do not edit by hand.
import * as S from "@kevinmichaelchen/distilled/schema";
import * as API from "@kevinmichaelchen/distilled/api";
import * as T from "../traits.ts";
import * as Retry from "../retry.ts";
import { TmdbProtocol, type TmdbOpError, type TmdbOpContext } from "../protocol.ts";

// Input Schema
export interface ConfigurationDetailsInput {  }
export const ConfigurationDetailsInput = /*@__PURE__*/ S.suspend(() =>
  S.Struct({

  }).pipe(T.Http({ method: "GET", uri: "/3/configuration", code: 200 }))
).annotate({ identifier: "ConfigurationDetailsInput" }) as unknown as S.Codec<ConfigurationDetailsInput>;

// Output Schema
export interface ConfigurationDetailsOutput { images?: { base_url?: string; secure_base_url?: string; backdrop_sizes?: ReadonlyArray<string>; logo_sizes?: ReadonlyArray<string>; poster_sizes?: ReadonlyArray<string>; profile_sizes?: ReadonlyArray<string>; still_sizes?: ReadonlyArray<string> }; change_keys?: ReadonlyArray<string> }
export const ConfigurationDetailsOutput = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    images: S.optional(S.Struct({
      base_url: S.optional(S.String),
      secure_base_url: S.optional(S.String),
      backdrop_sizes: S.optional(S.Array(S.String)),
      logo_sizes: S.optional(S.Array(S.String)),
      poster_sizes: S.optional(S.Array(S.String)),
      profile_sizes: S.optional(S.Array(S.String)),
      still_sizes: S.optional(S.Array(S.String)),
    })),
    change_keys: S.optional(S.Array(S.String)),
  })
).annotate({ identifier: "ConfigurationDetailsOutput" }) as unknown as S.Codec<ConfigurationDetailsOutput>;

// The operation
/**
 * Details
 *
 * Query the API configuration details.
 */
export type ConfigurationDetailsError = TmdbOpError;
export const configurationDetails: API.OperationMethod<
  ConfigurationDetailsInput,
  ConfigurationDetailsOutput,
  ConfigurationDetailsError,
  TmdbOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: ConfigurationDetailsInput,
  output: ConfigurationDetailsOutput,
  errors: [] as const,
  protocol: TmdbProtocol,
  retry: Retry.Retry,
}));

// Input Schema
export interface ConfigurationCountriesInput { language?: string }
export const ConfigurationCountriesInput = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    language: S.optional(S.String).pipe(T.Query("language")),
  }).pipe(T.Http({ method: "GET", uri: "/3/configuration/countries", code: 200 }))
).annotate({ identifier: "ConfigurationCountriesInput" }) as unknown as S.Codec<ConfigurationCountriesInput>;

// Output Schema
export type ConfigurationCountriesOutput = ReadonlyArray<{ iso_3166_1?: string; english_name?: string; native_name?: string }>;
export const ConfigurationCountriesOutput = /*@__PURE__*/ S.suspend(() =>
  S.Array(S.Struct({
    iso_3166_1: S.optional(S.String),
    english_name: S.optional(S.String),
    native_name: S.optional(S.String),
  }))
).annotate({ identifier: "ConfigurationCountriesOutput" }) as unknown as S.Codec<ConfigurationCountriesOutput>;

// The operation
/**
 * Countries
 *
 * Get the list of countries (ISO 3166-1 tags) used throughout TMDB.
 */
export type ConfigurationCountriesError = TmdbOpError;
export const configurationCountries: API.OperationMethod<
  ConfigurationCountriesInput,
  ConfigurationCountriesOutput,
  ConfigurationCountriesError,
  TmdbOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: ConfigurationCountriesInput,
  output: ConfigurationCountriesOutput,
  errors: [] as const,
  protocol: TmdbProtocol,
  retry: Retry.Retry,
}));

// Input Schema
export interface ConfigurationJobsInput {  }
export const ConfigurationJobsInput = /*@__PURE__*/ S.suspend(() =>
  S.Struct({

  }).pipe(T.Http({ method: "GET", uri: "/3/configuration/jobs", code: 200 }))
).annotate({ identifier: "ConfigurationJobsInput" }) as unknown as S.Codec<ConfigurationJobsInput>;

// Output Schema
export type ConfigurationJobsOutput = ReadonlyArray<{ department?: string; jobs?: ReadonlyArray<string> }>;
export const ConfigurationJobsOutput = /*@__PURE__*/ S.suspend(() =>
  S.Array(S.Struct({
    department: S.optional(S.String),
    jobs: S.optional(S.Array(S.String)),
  }))
).annotate({ identifier: "ConfigurationJobsOutput" }) as unknown as S.Codec<ConfigurationJobsOutput>;

// The operation
/**
 * Jobs
 *
 * Get the list of the jobs and departments we use on TMDB.
 */
export type ConfigurationJobsError = TmdbOpError;
export const configurationJobs: API.OperationMethod<
  ConfigurationJobsInput,
  ConfigurationJobsOutput,
  ConfigurationJobsError,
  TmdbOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: ConfigurationJobsInput,
  output: ConfigurationJobsOutput,
  errors: [] as const,
  protocol: TmdbProtocol,
  retry: Retry.Retry,
}));

// Input Schema
export interface ConfigurationLanguagesInput {  }
export const ConfigurationLanguagesInput = /*@__PURE__*/ S.suspend(() =>
  S.Struct({

  }).pipe(T.Http({ method: "GET", uri: "/3/configuration/languages", code: 200 }))
).annotate({ identifier: "ConfigurationLanguagesInput" }) as unknown as S.Codec<ConfigurationLanguagesInput>;

// Output Schema
export type ConfigurationLanguagesOutput = ReadonlyArray<{ iso_639_1?: string; english_name?: string; name?: string }>;
export const ConfigurationLanguagesOutput = /*@__PURE__*/ S.suspend(() =>
  S.Array(S.Struct({
    iso_639_1: S.optional(S.String),
    english_name: S.optional(S.String),
    name: S.optional(S.String),
  }))
).annotate({ identifier: "ConfigurationLanguagesOutput" }) as unknown as S.Codec<ConfigurationLanguagesOutput>;

// The operation
/**
 * Languages
 *
 * Get the list of languages (ISO 639-1 tags) used throughout TMDB.
 */
export type ConfigurationLanguagesError = TmdbOpError;
export const configurationLanguages: API.OperationMethod<
  ConfigurationLanguagesInput,
  ConfigurationLanguagesOutput,
  ConfigurationLanguagesError,
  TmdbOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: ConfigurationLanguagesInput,
  output: ConfigurationLanguagesOutput,
  errors: [] as const,
  protocol: TmdbProtocol,
  retry: Retry.Retry,
}));

// Input Schema
export interface ConfigurationPrimaryTranslationsInput {  }
export const ConfigurationPrimaryTranslationsInput = /*@__PURE__*/ S.suspend(() =>
  S.Struct({

  }).pipe(T.Http({ method: "GET", uri: "/3/configuration/primary_translations", code: 200 }))
).annotate({ identifier: "ConfigurationPrimaryTranslationsInput" }) as unknown as S.Codec<ConfigurationPrimaryTranslationsInput>;

// Output Schema
export type ConfigurationPrimaryTranslationsOutput = ReadonlyArray<string>;
export const ConfigurationPrimaryTranslationsOutput = /*@__PURE__*/ S.suspend(() =>
  S.Array(S.String)
).annotate({ identifier: "ConfigurationPrimaryTranslationsOutput" }) as unknown as S.Codec<ConfigurationPrimaryTranslationsOutput>;

// The operation
/**
 * Primary Translations
 *
 * Get a list of the officially supported translations on TMDB.
 */
export type ConfigurationPrimaryTranslationsError = TmdbOpError;
export const configurationPrimaryTranslations: API.OperationMethod<
  ConfigurationPrimaryTranslationsInput,
  ConfigurationPrimaryTranslationsOutput,
  ConfigurationPrimaryTranslationsError,
  TmdbOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: ConfigurationPrimaryTranslationsInput,
  output: ConfigurationPrimaryTranslationsOutput,
  errors: [] as const,
  protocol: TmdbProtocol,
  retry: Retry.Retry,
}));

// Input Schema
export interface ConfigurationTimezonesInput {  }
export const ConfigurationTimezonesInput = /*@__PURE__*/ S.suspend(() =>
  S.Struct({

  }).pipe(T.Http({ method: "GET", uri: "/3/configuration/timezones", code: 200 }))
).annotate({ identifier: "ConfigurationTimezonesInput" }) as unknown as S.Codec<ConfigurationTimezonesInput>;

// Output Schema
export type ConfigurationTimezonesOutput = ReadonlyArray<{ iso_3166_1?: string; zones?: ReadonlyArray<string> }>;
export const ConfigurationTimezonesOutput = /*@__PURE__*/ S.suspend(() =>
  S.Array(S.Struct({
    iso_3166_1: S.optional(S.String),
    zones: S.optional(S.Array(S.String)),
  }))
).annotate({ identifier: "ConfigurationTimezonesOutput" }) as unknown as S.Codec<ConfigurationTimezonesOutput>;

// The operation
/**
 * Timezones
 *
 * Get the list of timezones used throughout TMDB.
 */
export type ConfigurationTimezonesError = TmdbOpError;
export const configurationTimezones: API.OperationMethod<
  ConfigurationTimezonesInput,
  ConfigurationTimezonesOutput,
  ConfigurationTimezonesError,
  TmdbOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: ConfigurationTimezonesInput,
  output: ConfigurationTimezonesOutput,
  errors: [] as const,
  protocol: TmdbProtocol,
  retry: Retry.Retry,
}));
