// Generated by @kevinmichaelchen/distilled. Do not edit by hand.
import * as S from "@kevinmichaelchen/distilled/schema";
import * as API from "@kevinmichaelchen/distilled/api";
import * as T from "../traits.ts";
import * as Retry from "../retry.ts";
import { TmdbProtocol, type TmdbOpError, type TmdbOpContext } from "../protocol.ts";

// Input Schema
export interface CreditDetailsInput { credit_id: string; language?: string }
export const CreditDetailsInput = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    credit_id: S.String.pipe(T.Label("credit_id")),
    language: S.optional(S.String).pipe(T.Query("language")),
  }).pipe(T.Http({ method: "GET", uri: "/3/credit/{credit_id}", code: 200 }))
).annotate({ identifier: "CreditDetailsInput" }) as unknown as S.Codec<CreditDetailsInput>;

// Output Schema
export interface CreditDetailsOutput { credit_type?: string; department?: string; job?: string; media?: { adult?: boolean; backdrop_path?: string; id?: number; name?: string; original_language?: string; original_name?: string; overview?: string; poster_path?: string; media_type?: string; genre_ids?: ReadonlyArray<number>; popularity?: number; first_air_date?: string; vote_average?: number; vote_count?: number; origin_country?: ReadonlyArray<string>; character?: string; episodes?: ReadonlyArray<unknown>; seasons?: ReadonlyArray<{ air_date?: string; episode_count?: number; id?: number; name?: string; overview?: string; poster_path?: string; season_number?: number; show_id?: number }> }; media_type?: string; id?: string; person?: { adult?: boolean; id?: number; name?: string; original_name?: string; media_type?: string; popularity?: number; gender?: number; known_for_department?: string; profile_path?: string } }
export const CreditDetailsOutput = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    credit_type: S.optional(S.String),
    department: S.optional(S.String),
    job: S.optional(S.String),
    media: S.optional(S.Struct({
      adult: S.optional(S.Boolean),
      backdrop_path: S.optional(S.String),
      id: S.optional(S.Number),
      name: S.optional(S.String),
      original_language: S.optional(S.String),
      original_name: S.optional(S.String),
      overview: S.optional(S.String),
      poster_path: S.optional(S.String),
      media_type: S.optional(S.String),
      genre_ids: S.optional(S.Array(S.Number)),
      popularity: S.optional(S.Number),
      first_air_date: S.optional(S.String),
      vote_average: S.optional(S.Number),
      vote_count: S.optional(S.Number),
      origin_country: S.optional(S.Array(S.String)),
      character: S.optional(S.String),
      episodes: S.optional(S.Array(S.Unknown)),
      seasons: S.optional(S.Array(S.Struct({
        air_date: S.optional(S.String),
        episode_count: S.optional(S.Number),
        id: S.optional(S.Number),
        name: S.optional(S.String),
        overview: S.optional(S.String),
        poster_path: S.optional(S.String),
        season_number: S.optional(S.Number),
        show_id: S.optional(S.Number),
      }))),
    })),
    media_type: S.optional(S.String),
    id: S.optional(S.String),
    person: S.optional(S.Struct({
      adult: S.optional(S.Boolean),
      id: S.optional(S.Number),
      name: S.optional(S.String),
      original_name: S.optional(S.String),
      media_type: S.optional(S.String),
      popularity: S.optional(S.Number),
      gender: S.optional(S.Number),
      known_for_department: S.optional(S.String),
      profile_path: S.optional(S.String),
    })),
  })
).annotate({ identifier: "CreditDetailsOutput" }) as unknown as S.Codec<CreditDetailsOutput>;

// The operation
/**
 * Details
 *
 * Get a movie or TV credit details by ID.
 */
export type CreditDetailsError = TmdbOpError;
export const creditDetails: API.OperationMethod<
  CreditDetailsInput,
  CreditDetailsOutput,
  CreditDetailsError,
  TmdbOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: CreditDetailsInput,
  output: CreditDetailsOutput,
  errors: [] as const,
  protocol: TmdbProtocol,
  retry: Retry.Retry,
}));
