// Generated by @kevinmichaelchen/distilled. Do not edit by hand.
import * as S from "@kevinmichaelchen/distilled/schema";
import * as API from "@kevinmichaelchen/distilled/api";
import * as T from "../traits.ts";
import * as Retry from "../retry.ts";
import { TmdbProtocol, type TmdbOpError, type TmdbOpContext } from "../protocol.ts";

// Input Schema
export interface DiscoverMovieInput { certification?: string; "certification.gte"?: string; "certification.lte"?: string; certification_country?: string; include_adult?: boolean; include_video?: boolean; language?: string; page?: number; primary_release_year?: number; "primary_release_date.gte"?: string; "primary_release_date.lte"?: string; region?: string; "release_date.gte"?: string; "release_date.lte"?: string; sort_by?: "original_title.asc" | "original_title.desc" | "popularity.asc" | "popularity.desc" | "revenue.asc" | "revenue.desc" | "primary_release_date.asc" | "title.asc" | "title.desc" | "primary_release_date.desc" | "vote_average.asc" | "vote_average.desc" | "vote_count.asc" | "vote_count.desc"; "vote_average.gte"?: number; "vote_average.lte"?: number; "vote_count.gte"?: number; "vote_count.lte"?: number; watch_region?: string; with_cast?: string; with_companies?: string; with_crew?: string; with_genres?: string; with_keywords?: string; with_origin_country?: string; with_original_language?: string; with_people?: string; with_release_type?: number; "with_runtime.gte"?: number; "with_runtime.lte"?: number; with_watch_monetization_types?: string; with_watch_providers?: string; without_companies?: string; without_genres?: string; without_keywords?: string; without_watch_providers?: string; year?: number }
export const DiscoverMovieInput = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    certification: S.optional(S.String).pipe(T.Query("certification")),
    "certification.gte": S.optional(S.String).pipe(T.Query("certification.gte")),
    "certification.lte": S.optional(S.String).pipe(T.Query("certification.lte")),
    certification_country: S.optional(S.String).pipe(T.Query("certification_country")),
    include_adult: S.optional(S.Boolean).pipe(T.Query("include_adult")),
    include_video: S.optional(S.Boolean).pipe(T.Query("include_video")),
    language: S.optional(S.String).pipe(T.Query("language")),
    page: S.optional(S.Number).pipe(T.Query("page")),
    primary_release_year: S.optional(S.Number).pipe(T.Query("primary_release_year")),
    "primary_release_date.gte": S.optional(S.String).pipe(T.Query("primary_release_date.gte")),
    "primary_release_date.lte": S.optional(S.String).pipe(T.Query("primary_release_date.lte")),
    region: S.optional(S.String).pipe(T.Query("region")),
    "release_date.gte": S.optional(S.String).pipe(T.Query("release_date.gte")),
    "release_date.lte": S.optional(S.String).pipe(T.Query("release_date.lte")),
    sort_by: S.optional(S.Literals(["original_title.asc", "original_title.desc", "popularity.asc", "popularity.desc", "revenue.asc", "revenue.desc", "primary_release_date.asc", "title.asc", "title.desc", "primary_release_date.desc", "vote_average.asc", "vote_average.desc", "vote_count.asc", "vote_count.desc"])).pipe(T.Query("sort_by")),
    "vote_average.gte": S.optional(S.Number).pipe(T.Query("vote_average.gte")),
    "vote_average.lte": S.optional(S.Number).pipe(T.Query("vote_average.lte")),
    "vote_count.gte": S.optional(S.Number).pipe(T.Query("vote_count.gte")),
    "vote_count.lte": S.optional(S.Number).pipe(T.Query("vote_count.lte")),
    watch_region: S.optional(S.String).pipe(T.Query("watch_region")),
    with_cast: S.optional(S.String).pipe(T.Query("with_cast")),
    with_companies: S.optional(S.String).pipe(T.Query("with_companies")),
    with_crew: S.optional(S.String).pipe(T.Query("with_crew")),
    with_genres: S.optional(S.String).pipe(T.Query("with_genres")),
    with_keywords: S.optional(S.String).pipe(T.Query("with_keywords")),
    with_origin_country: S.optional(S.String).pipe(T.Query("with_origin_country")),
    with_original_language: S.optional(S.String).pipe(T.Query("with_original_language")),
    with_people: S.optional(S.String).pipe(T.Query("with_people")),
    with_release_type: S.optional(S.Number).pipe(T.Query("with_release_type")),
    "with_runtime.gte": S.optional(S.Number).pipe(T.Query("with_runtime.gte")),
    "with_runtime.lte": S.optional(S.Number).pipe(T.Query("with_runtime.lte")),
    with_watch_monetization_types: S.optional(S.String).pipe(T.Query("with_watch_monetization_types")),
    with_watch_providers: S.optional(S.String).pipe(T.Query("with_watch_providers")),
    without_companies: S.optional(S.String).pipe(T.Query("without_companies")),
    without_genres: S.optional(S.String).pipe(T.Query("without_genres")),
    without_keywords: S.optional(S.String).pipe(T.Query("without_keywords")),
    without_watch_providers: S.optional(S.String).pipe(T.Query("without_watch_providers")),
    year: S.optional(S.Number).pipe(T.Query("year")),
  }).pipe(T.Http({ method: "GET", uri: "/3/discover/movie", code: 200 }))
).annotate({ identifier: "DiscoverMovieInput" }) as unknown as S.Codec<DiscoverMovieInput>;

// Output Schema
export interface DiscoverMovieOutput { page?: number; results?: ReadonlyArray<{ adult?: boolean; backdrop_path?: string; genre_ids?: ReadonlyArray<number>; id?: number; original_language?: string; original_title?: string; overview?: string; popularity?: number; poster_path?: string; release_date?: string; title?: string; video?: boolean; vote_average?: number; vote_count?: number }>; total_pages?: number; total_results?: number }
export const DiscoverMovieOutput = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    page: S.optional(S.Number),
    results: S.optional(S.Array(S.Struct({
      adult: S.optional(S.Boolean),
      backdrop_path: S.optional(S.String),
      genre_ids: S.optional(S.Array(S.Number)),
      id: S.optional(S.Number),
      original_language: S.optional(S.String),
      original_title: S.optional(S.String),
      overview: S.optional(S.String),
      popularity: S.optional(S.Number),
      poster_path: S.optional(S.String),
      release_date: S.optional(S.String),
      title: S.optional(S.String),
      video: S.optional(S.Boolean),
      vote_average: S.optional(S.Number),
      vote_count: S.optional(S.Number),
    }))),
    total_pages: S.optional(S.Number),
    total_results: S.optional(S.Number),
  })
).annotate({ identifier: "DiscoverMovieOutput" }) as unknown as S.Codec<DiscoverMovieOutput>;

// The operation
/**
 * Movie
 *
 * Find movies using over 30 filters and sort options.
 *
 * @param certification - use in conjunction with `region`
 * @param certification.gte - use in conjunction with `region`
 * @param certification.lte - use in conjunction with `region`
 * @param certification_country - use in conjunction with the `certification`, `certification.gte` and `certification.lte` filters
 * @param watch_region - use in conjunction with `with_watch_monetization_types ` or `with_watch_providers `
 * @param with_cast - can be a comma (`AND`) or pipe (`OR`) separated query
 * @param with_companies - can be a comma (`AND`) or pipe (`OR`) separated query
 * @param with_crew - can be a comma (`AND`) or pipe (`OR`) separated query
 * @param with_genres - can be a comma (`AND`) or pipe (`OR`) separated query
 * @param with_keywords - can be a comma (`AND`) or pipe (`OR`) separated query
 * @param with_people - can be a comma (`AND`) or pipe (`OR`) separated query
 * @param with_release_type - possible values are: [1, 2, 3, 4, 5, 6] can be a comma (`AND`) or pipe (`OR`) separated query, can be used in conjunction with `region`
 * @param with_watch_monetization_types - possible values are: [flatrate, free, ads, rent, buy] use in conjunction with `watch_region`, can be a comma (`AND`) or pipe (`OR`) separated query
 * @param with_watch_providers - use in conjunction with `watch_region`, can be a comma (`AND`) or pipe (`OR`) separated query
 */
export type DiscoverMovieError = TmdbOpError;
export const discoverMovie: API.OperationMethod<
  DiscoverMovieInput,
  DiscoverMovieOutput,
  DiscoverMovieError,
  TmdbOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: DiscoverMovieInput,
  output: DiscoverMovieOutput,
  errors: [] as const,
  protocol: TmdbProtocol,
  retry: Retry.Retry,
}));

// Input Schema
export interface DiscoverTvInput { "air_date.gte"?: string; "air_date.lte"?: string; first_air_date_year?: number; "first_air_date.gte"?: string; "first_air_date.lte"?: string; include_adult?: boolean; include_null_first_air_dates?: boolean; language?: string; page?: number; screened_theatrically?: boolean; sort_by?: "first_air_date.asc" | "first_air_date.desc" | "name.asc" | "name.desc" | "original_name.asc" | "original_name.desc" | "popularity.asc" | "popularity.desc" | "vote_average.asc" | "vote_average.desc" | "vote_count.asc" | "vote_count.desc"; timezone?: string; "vote_average.gte"?: number; "vote_average.lte"?: number; "vote_count.gte"?: number; "vote_count.lte"?: number; watch_region?: string; with_companies?: string; with_genres?: string; with_keywords?: string; with_networks?: number; with_origin_country?: string; with_original_language?: string; "with_runtime.gte"?: number; "with_runtime.lte"?: number; with_status?: string; with_watch_monetization_types?: string; with_watch_providers?: string; without_companies?: string; without_genres?: string; without_keywords?: string; without_watch_providers?: string; with_type?: string }
export const DiscoverTvInput = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    "air_date.gte": S.optional(S.String).pipe(T.Query("air_date.gte")),
    "air_date.lte": S.optional(S.String).pipe(T.Query("air_date.lte")),
    first_air_date_year: S.optional(S.Number).pipe(T.Query("first_air_date_year")),
    "first_air_date.gte": S.optional(S.String).pipe(T.Query("first_air_date.gte")),
    "first_air_date.lte": S.optional(S.String).pipe(T.Query("first_air_date.lte")),
    include_adult: S.optional(S.Boolean).pipe(T.Query("include_adult")),
    include_null_first_air_dates: S.optional(S.Boolean).pipe(T.Query("include_null_first_air_dates")),
    language: S.optional(S.String).pipe(T.Query("language")),
    page: S.optional(S.Number).pipe(T.Query("page")),
    screened_theatrically: S.optional(S.Boolean).pipe(T.Query("screened_theatrically")),
    sort_by: S.optional(S.Literals(["first_air_date.asc", "first_air_date.desc", "name.asc", "name.desc", "original_name.asc", "original_name.desc", "popularity.asc", "popularity.desc", "vote_average.asc", "vote_average.desc", "vote_count.asc", "vote_count.desc"])).pipe(T.Query("sort_by")),
    timezone: S.optional(S.String).pipe(T.Query("timezone")),
    "vote_average.gte": S.optional(S.Number).pipe(T.Query("vote_average.gte")),
    "vote_average.lte": S.optional(S.Number).pipe(T.Query("vote_average.lte")),
    "vote_count.gte": S.optional(S.Number).pipe(T.Query("vote_count.gte")),
    "vote_count.lte": S.optional(S.Number).pipe(T.Query("vote_count.lte")),
    watch_region: S.optional(S.String).pipe(T.Query("watch_region")),
    with_companies: S.optional(S.String).pipe(T.Query("with_companies")),
    with_genres: S.optional(S.String).pipe(T.Query("with_genres")),
    with_keywords: S.optional(S.String).pipe(T.Query("with_keywords")),
    with_networks: S.optional(S.Number).pipe(T.Query("with_networks")),
    with_origin_country: S.optional(S.String).pipe(T.Query("with_origin_country")),
    with_original_language: S.optional(S.String).pipe(T.Query("with_original_language")),
    "with_runtime.gte": S.optional(S.Number).pipe(T.Query("with_runtime.gte")),
    "with_runtime.lte": S.optional(S.Number).pipe(T.Query("with_runtime.lte")),
    with_status: S.optional(S.String).pipe(T.Query("with_status")),
    with_watch_monetization_types: S.optional(S.String).pipe(T.Query("with_watch_monetization_types")),
    with_watch_providers: S.optional(S.String).pipe(T.Query("with_watch_providers")),
    without_companies: S.optional(S.String).pipe(T.Query("without_companies")),
    without_genres: S.optional(S.String).pipe(T.Query("without_genres")),
    without_keywords: S.optional(S.String).pipe(T.Query("without_keywords")),
    without_watch_providers: S.optional(S.String).pipe(T.Query("without_watch_providers")),
    with_type: S.optional(S.String).pipe(T.Query("with_type")),
  }).pipe(T.Http({ method: "GET", uri: "/3/discover/tv", code: 200 }))
).annotate({ identifier: "DiscoverTvInput" }) as unknown as S.Codec<DiscoverTvInput>;

// Output Schema
export interface DiscoverTvOutput { page?: number; results?: ReadonlyArray<{ backdrop_path?: string; first_air_date?: string; genre_ids?: ReadonlyArray<number>; id?: number; name?: string; origin_country?: ReadonlyArray<string>; original_language?: string; original_name?: string; overview?: string; popularity?: number; poster_path?: string; vote_average?: number; vote_count?: number }>; total_pages?: number; total_results?: number }
export const DiscoverTvOutput = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    page: S.optional(S.Number),
    results: S.optional(S.Array(S.Struct({
      backdrop_path: S.optional(S.String),
      first_air_date: S.optional(S.String),
      genre_ids: S.optional(S.Array(S.Number)),
      id: S.optional(S.Number),
      name: S.optional(S.String),
      origin_country: S.optional(S.Array(S.String)),
      original_language: S.optional(S.String),
      original_name: S.optional(S.String),
      overview: S.optional(S.String),
      popularity: S.optional(S.Number),
      poster_path: S.optional(S.String),
      vote_average: S.optional(S.Number),
      vote_count: S.optional(S.Number),
    }))),
    total_pages: S.optional(S.Number),
    total_results: S.optional(S.Number),
  })
).annotate({ identifier: "DiscoverTvOutput" }) as unknown as S.Codec<DiscoverTvOutput>;

// The operation
/**
 * TV
 *
 * Find TV shows using over 30 filters and sort options.
 *
 * @param watch_region - use in conjunction with `with_watch_monetization_types ` or `with_watch_providers `
 * @param with_companies - can be a comma (`AND`) or pipe (`OR`) separated query
 * @param with_genres - can be a comma (`AND`) or pipe (`OR`) separated query
 * @param with_keywords - can be a comma (`AND`) or pipe (`OR`) separated query
 * @param with_status - possible values are: [0, 1, 2, 3, 4, 5], can be a comma (`AND`) or pipe (`OR`) separated query
 * @param with_watch_monetization_types - possible values are: [flatrate, free, ads, rent, buy] use in conjunction with `watch_region`, can be a comma (`AND`) or pipe (`OR`) separated query
 * @param with_watch_providers - use in conjunction with `watch_region`, can be a comma (`AND`) or pipe (`OR`) separated query
 * @param with_type - possible values are: [0, 1, 2, 3, 4, 5, 6], can be a comma (`AND`) or pipe (`OR`) separated query
 */
export type DiscoverTvError = TmdbOpError;
export const discoverTv: API.OperationMethod<
  DiscoverTvInput,
  DiscoverTvOutput,
  DiscoverTvError,
  TmdbOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: DiscoverTvInput,
  output: DiscoverTvOutput,
  errors: [] as const,
  protocol: TmdbProtocol,
  retry: Retry.Retry,
}));
