// Generated by @kevinmichaelchen/distilled. Do not edit by hand.
import * as S from "@kevinmichaelchen/distilled/schema";
import * as API from "@kevinmichaelchen/distilled/api";
import * as T from "../traits.ts";
import * as Retry from "../retry.ts";
import { TmdbProtocol, type TmdbOpError, type TmdbOpContext } from "../protocol.ts";

// Input Schema
export interface FindByIdInput { external_id: string; external_source: "imdb_id" | "facebook_id" | "instagram_id" | "tvdb_id" | "tiktok_id" | "twitter_id" | "wikidata_id" | "youtube_id"; language?: string }
export const FindByIdInput = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    external_id: S.String.pipe(T.Label("external_id")),
    external_source: S.Literals(["imdb_id", "facebook_id", "instagram_id", "tvdb_id", "tiktok_id", "twitter_id", "wikidata_id", "youtube_id"]).pipe(T.Query("external_source")),
    language: S.optional(S.String).pipe(T.Query("language")),
  }).pipe(T.Http({ method: "GET", uri: "/3/find/{external_id}", code: 200 }))
).annotate({ identifier: "FindByIdInput" }) as unknown as S.Codec<FindByIdInput>;

// Output Schema
export interface FindByIdOutput { movie_results?: ReadonlyArray<{ adult?: boolean; backdrop_path?: string; id?: number; title?: string; original_language?: string; original_title?: string; overview?: string; poster_path?: string; media_type?: string; genre_ids?: ReadonlyArray<number>; popularity?: number; release_date?: string; video?: boolean; vote_average?: number; vote_count?: number }>; person_results?: ReadonlyArray<unknown>; tv_results?: ReadonlyArray<unknown>; tv_episode_results?: ReadonlyArray<unknown>; tv_season_results?: ReadonlyArray<unknown> }
export const FindByIdOutput = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    movie_results: S.optional(S.Array(S.Struct({
      adult: S.optional(S.Boolean),
      backdrop_path: S.optional(S.String),
      id: S.optional(S.Number),
      title: S.optional(S.String),
      original_language: S.optional(S.String),
      original_title: S.optional(S.String),
      overview: S.optional(S.String),
      poster_path: S.optional(S.String),
      media_type: S.optional(S.String),
      genre_ids: S.optional(S.Array(S.Number)),
      popularity: S.optional(S.Number),
      release_date: S.optional(S.String),
      video: S.optional(S.Boolean),
      vote_average: S.optional(S.Number),
      vote_count: S.optional(S.Number),
    }))),
    person_results: S.optional(S.Array(S.Unknown)),
    tv_results: S.optional(S.Array(S.Unknown)),
    tv_episode_results: S.optional(S.Array(S.Unknown)),
    tv_season_results: S.optional(S.Array(S.Unknown)),
  })
).annotate({ identifier: "FindByIdOutput" }) as unknown as S.Codec<FindByIdOutput>;

// The operation
/**
 * Find By ID
 *
 * Find data by external ID's.
 */
export type FindByIdError = TmdbOpError;
export const findById: API.OperationMethod<
  FindByIdInput,
  FindByIdOutput,
  FindByIdError,
  TmdbOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: FindByIdInput,
  output: FindByIdOutput,
  errors: [] as const,
  protocol: TmdbProtocol,
  retry: Retry.Retry,
}));
