// Generated by @kevinmichaelchen/distilled. Do not edit by hand.
import * as S from "@kevinmichaelchen/distilled/schema";
import * as API from "@kevinmichaelchen/distilled/api";
import * as T from "../traits.ts";
import * as Retry from "../retry.ts";
import { TmdbProtocol, type TmdbOpError, type TmdbOpContext } from "../protocol.ts";

// Input Schema
export interface GenreMovieListInput { language?: string }
export const GenreMovieListInput = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    language: S.optional(S.String).pipe(T.Query("language")),
  }).pipe(T.Http({ method: "GET", uri: "/3/genre/movie/list", code: 200 }))
).annotate({ identifier: "GenreMovieListInput" }) as unknown as S.Codec<GenreMovieListInput>;

// Output Schema
export interface GenreMovieListOutput { genres?: ReadonlyArray<{ id?: number; name?: string }> }
export const GenreMovieListOutput = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    genres: S.optional(S.Array(S.Struct({
      id: S.optional(S.Number),
      name: S.optional(S.String),
    }))),
  })
).annotate({ identifier: "GenreMovieListOutput" }) as unknown as S.Codec<GenreMovieListOutput>;

// The operation
/**
 * Movie List
 *
 * Get the list of official genres for movies.
 */
export type GenreMovieListError = TmdbOpError;
export const genreMovieList: API.OperationMethod<
  GenreMovieListInput,
  GenreMovieListOutput,
  GenreMovieListError,
  TmdbOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: GenreMovieListInput,
  output: GenreMovieListOutput,
  errors: [] as const,
  protocol: TmdbProtocol,
  retry: Retry.Retry,
}));

// Input Schema
export interface GenreTvListInput { language?: string }
export const GenreTvListInput = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    language: S.optional(S.String).pipe(T.Query("language")),
  }).pipe(T.Http({ method: "GET", uri: "/3/genre/tv/list", code: 200 }))
).annotate({ identifier: "GenreTvListInput" }) as unknown as S.Codec<GenreTvListInput>;

// Output Schema
export interface GenreTvListOutput { genres?: ReadonlyArray<{ id?: number; name?: string }> }
export const GenreTvListOutput = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    genres: S.optional(S.Array(S.Struct({
      id: S.optional(S.Number),
      name: S.optional(S.String),
    }))),
  })
).annotate({ identifier: "GenreTvListOutput" }) as unknown as S.Codec<GenreTvListOutput>;

// The operation
/**
 * TV List
 *
 * Get the list of official genres for TV shows.
 */
export type GenreTvListError = TmdbOpError;
export const genreTvList: API.OperationMethod<
  GenreTvListInput,
  GenreTvListOutput,
  GenreTvListError,
  TmdbOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: GenreTvListInput,
  output: GenreTvListOutput,
  errors: [] as const,
  protocol: TmdbProtocol,
  retry: Retry.Retry,
}));
