// Generated by @kevinmichaelchen/distilled. Do not edit by hand.
import * as S from "@kevinmichaelchen/distilled/schema";
import * as API from "@kevinmichaelchen/distilled/api";
import * as T from "../traits.ts";
import * as Retry from "../retry.ts";
import { TmdbProtocol, type TmdbOpError, type TmdbOpContext } from "../protocol.ts";

// Input Schema
export interface GuestSessionRatedMoviesInput { guest_session_id: string; language?: string; page?: number; sort_by?: "created_at.asc" | "created_at.desc" }
export const GuestSessionRatedMoviesInput = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    guest_session_id: S.String.pipe(T.Label("guest_session_id")),
    language: S.optional(S.String).pipe(T.Query("language")),
    page: S.optional(S.Number).pipe(T.Query("page")),
    sort_by: S.optional(S.Literals(["created_at.asc", "created_at.desc"])).pipe(T.Query("sort_by")),
  }).pipe(T.Http({ method: "GET", uri: "/3/guest_session/{guest_session_id}/rated/movies", code: 200 }))
).annotate({ identifier: "GuestSessionRatedMoviesInput" }) as unknown as S.Codec<GuestSessionRatedMoviesInput>;

// Output Schema
export interface GuestSessionRatedMoviesOutput { page?: number; results?: ReadonlyArray<{ adult?: boolean; backdrop_path?: string; genre_ids?: ReadonlyArray<number>; id?: number; original_language?: string; original_title?: string; overview?: string; popularity?: number; poster_path?: string; release_date?: string; title?: string; video?: boolean; vote_average?: number; vote_count?: number; rating?: number }>; total_pages?: number; total_results?: number }
export const GuestSessionRatedMoviesOutput = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    page: S.optional(S.Number),
    results: S.optional(S.Array(S.Struct({
      adult: S.optional(S.Boolean),
      backdrop_path: S.optional(S.String),
      genre_ids: S.optional(S.Array(S.Number)),
      id: S.optional(S.Number),
      original_language: S.optional(S.String),
      original_title: S.optional(S.String),
      overview: S.optional(S.String),
      popularity: S.optional(S.Number),
      poster_path: S.optional(S.String),
      release_date: S.optional(S.String),
      title: S.optional(S.String),
      video: S.optional(S.Boolean),
      vote_average: S.optional(S.Number),
      vote_count: S.optional(S.Number),
      rating: S.optional(S.Number),
    }))),
    total_pages: S.optional(S.Number),
    total_results: S.optional(S.Number),
  })
).annotate({ identifier: "GuestSessionRatedMoviesOutput" }) as unknown as S.Codec<GuestSessionRatedMoviesOutput>;

// The operation
/**
 * Rated Movies
 *
 * Get the rated movies for a guest session.
 */
export type GuestSessionRatedMoviesError = TmdbOpError;
export const guestSessionRatedMovies: API.OperationMethod<
  GuestSessionRatedMoviesInput,
  GuestSessionRatedMoviesOutput,
  GuestSessionRatedMoviesError,
  TmdbOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: GuestSessionRatedMoviesInput,
  output: GuestSessionRatedMoviesOutput,
  errors: [] as const,
  protocol: TmdbProtocol,
  retry: Retry.Retry,
}));

// Input Schema
export interface GuestSessionRatedTvInput { guest_session_id: string; language?: string; page?: number; sort_by?: "created_at.asc" | "created_at.desc" }
export const GuestSessionRatedTvInput = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    guest_session_id: S.String.pipe(T.Label("guest_session_id")),
    language: S.optional(S.String).pipe(T.Query("language")),
    page: S.optional(S.Number).pipe(T.Query("page")),
    sort_by: S.optional(S.Literals(["created_at.asc", "created_at.desc"])).pipe(T.Query("sort_by")),
  }).pipe(T.Http({ method: "GET", uri: "/3/guest_session/{guest_session_id}/rated/tv", code: 200 }))
).annotate({ identifier: "GuestSessionRatedTvInput" }) as unknown as S.Codec<GuestSessionRatedTvInput>;

// Output Schema
export interface GuestSessionRatedTvOutput { page?: number; results?: ReadonlyArray<{ adult?: boolean; backdrop_path?: string; genre_ids?: ReadonlyArray<number>; id?: number; origin_country?: ReadonlyArray<string>; original_language?: string; original_name?: string; overview?: string; popularity?: number; poster_path?: string; first_air_date?: string; name?: string; vote_average?: number; vote_count?: number; rating?: number }>; total_pages?: number; total_results?: number }
export const GuestSessionRatedTvOutput = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    page: S.optional(S.Number),
    results: S.optional(S.Array(S.Struct({
      adult: S.optional(S.Boolean),
      backdrop_path: S.optional(S.String),
      genre_ids: S.optional(S.Array(S.Number)),
      id: S.optional(S.Number),
      origin_country: S.optional(S.Array(S.String)),
      original_language: S.optional(S.String),
      original_name: S.optional(S.String),
      overview: S.optional(S.String),
      popularity: S.optional(S.Number),
      poster_path: S.optional(S.String),
      first_air_date: S.optional(S.String),
      name: S.optional(S.String),
      vote_average: S.optional(S.Number),
      vote_count: S.optional(S.Number),
      rating: S.optional(S.Number),
    }))),
    total_pages: S.optional(S.Number),
    total_results: S.optional(S.Number),
  })
).annotate({ identifier: "GuestSessionRatedTvOutput" }) as unknown as S.Codec<GuestSessionRatedTvOutput>;

// The operation
/**
 * Rated TV
 *
 * Get the rated TV shows for a guest session.
 */
export type GuestSessionRatedTvError = TmdbOpError;
export const guestSessionRatedTv: API.OperationMethod<
  GuestSessionRatedTvInput,
  GuestSessionRatedTvOutput,
  GuestSessionRatedTvError,
  TmdbOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: GuestSessionRatedTvInput,
  output: GuestSessionRatedTvOutput,
  errors: [] as const,
  protocol: TmdbProtocol,
  retry: Retry.Retry,
}));

// Input Schema
export interface GuestSessionRatedTvEpisodesInput { guest_session_id: string; language?: string; page?: number; sort_by?: "created_at.asc" | "created_at.desc" }
export const GuestSessionRatedTvEpisodesInput = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    guest_session_id: S.String.pipe(T.Label("guest_session_id")),
    language: S.optional(S.String).pipe(T.Query("language")),
    page: S.optional(S.Number).pipe(T.Query("page")),
    sort_by: S.optional(S.Literals(["created_at.asc", "created_at.desc"])).pipe(T.Query("sort_by")),
  }).pipe(T.Http({ method: "GET", uri: "/3/guest_session/{guest_session_id}/rated/tv/episodes", code: 200 }))
).annotate({ identifier: "GuestSessionRatedTvEpisodesInput" }) as unknown as S.Codec<GuestSessionRatedTvEpisodesInput>;

// Output Schema
export interface GuestSessionRatedTvEpisodesOutput { page?: number; results?: ReadonlyArray<{ air_date?: string; episode_number?: number; id?: number; name?: string; overview?: string; production_code?: string; runtime?: number; season_number?: number; show_id?: number; still_path?: string; vote_average?: number; vote_count?: number; rating?: number }>; total_pages?: number; total_results?: number }
export const GuestSessionRatedTvEpisodesOutput = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    page: S.optional(S.Number),
    results: S.optional(S.Array(S.Struct({
      air_date: S.optional(S.String),
      episode_number: S.optional(S.Number),
      id: S.optional(S.Number),
      name: S.optional(S.String),
      overview: S.optional(S.String),
      production_code: S.optional(S.String),
      runtime: S.optional(S.Number),
      season_number: S.optional(S.Number),
      show_id: S.optional(S.Number),
      still_path: S.optional(S.String),
      vote_average: S.optional(S.Number),
      vote_count: S.optional(S.Number),
      rating: S.optional(S.Number),
    }))),
    total_pages: S.optional(S.Number),
    total_results: S.optional(S.Number),
  })
).annotate({ identifier: "GuestSessionRatedTvEpisodesOutput" }) as unknown as S.Codec<GuestSessionRatedTvEpisodesOutput>;

// The operation
/**
 * Rated TV Episodes
 *
 * Get the rated TV episodes for a guest session.
 */
export type GuestSessionRatedTvEpisodesError = TmdbOpError;
export const guestSessionRatedTvEpisodes: API.OperationMethod<
  GuestSessionRatedTvEpisodesInput,
  GuestSessionRatedTvEpisodesOutput,
  GuestSessionRatedTvEpisodesError,
  TmdbOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: GuestSessionRatedTvEpisodesInput,
  output: GuestSessionRatedTvEpisodesOutput,
  errors: [] as const,
  protocol: TmdbProtocol,
  retry: Retry.Retry,
}));
