// Generated by @kevinmichaelchen/distilled. Do not edit by hand.
import * as S from "@kevinmichaelchen/distilled/schema";
import * as API from "@kevinmichaelchen/distilled/api";
import * as T from "../traits.ts";
import * as Retry from "../retry.ts";
import { TmdbProtocol, type TmdbOpError, type TmdbOpContext } from "../protocol.ts";

// Input Schema
export interface KeywordDetailsInput { keyword_id: number }
export const KeywordDetailsInput = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    keyword_id: S.Number.pipe(T.Label("keyword_id")),
  }).pipe(T.Http({ method: "GET", uri: "/3/keyword/{keyword_id}", code: 200 }))
).annotate({ identifier: "KeywordDetailsInput" }) as unknown as S.Codec<KeywordDetailsInput>;

// Output Schema
export interface KeywordDetailsOutput { id?: number; name?: string }
export const KeywordDetailsOutput = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.optional(S.Number),
    name: S.optional(S.String),
  })
).annotate({ identifier: "KeywordDetailsOutput" }) as unknown as S.Codec<KeywordDetailsOutput>;

// The operation
/**
 * Details
 */
export type KeywordDetailsError = TmdbOpError;
export const keywordDetails: API.OperationMethod<
  KeywordDetailsInput,
  KeywordDetailsOutput,
  KeywordDetailsError,
  TmdbOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: KeywordDetailsInput,
  output: KeywordDetailsOutput,
  errors: [] as const,
  protocol: TmdbProtocol,
  retry: Retry.Retry,
}));

// Input Schema
export interface KeywordMoviesInput { keyword_id: string; include_adult?: boolean; language?: string; page?: number }
export const KeywordMoviesInput = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    keyword_id: S.String.pipe(T.Label("keyword_id")),
    include_adult: S.optional(S.Boolean).pipe(T.Query("include_adult")),
    language: S.optional(S.String).pipe(T.Query("language")),
    page: S.optional(S.Number).pipe(T.Query("page")),
  }).pipe(T.Http({ method: "GET", uri: "/3/keyword/{keyword_id}/movies", code: 200 }))
).annotate({ identifier: "KeywordMoviesInput" }) as unknown as S.Codec<KeywordMoviesInput>;

// Output Schema
export interface KeywordMoviesOutput { id?: number; page?: number; results?: ReadonlyArray<{ adult?: boolean; backdrop_path?: string; genre_ids?: ReadonlyArray<number>; id?: number; original_language?: string; original_title?: string; overview?: string; popularity?: number; poster_path?: string; release_date?: string; title?: string; video?: boolean; vote_average?: number; vote_count?: number }>; total_pages?: number; total_results?: number }
export const KeywordMoviesOutput = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.optional(S.Number),
    page: S.optional(S.Number),
    results: S.optional(S.Array(S.Struct({
      adult: S.optional(S.Boolean),
      backdrop_path: S.optional(S.String),
      genre_ids: S.optional(S.Array(S.Number)),
      id: S.optional(S.Number),
      original_language: S.optional(S.String),
      original_title: S.optional(S.String),
      overview: S.optional(S.String),
      popularity: S.optional(S.Number),
      poster_path: S.optional(S.String),
      release_date: S.optional(S.String),
      title: S.optional(S.String),
      video: S.optional(S.Boolean),
      vote_average: S.optional(S.Number),
      vote_count: S.optional(S.Number),
    }))),
    total_pages: S.optional(S.Number),
    total_results: S.optional(S.Number),
  })
).annotate({ identifier: "KeywordMoviesOutput" }) as unknown as S.Codec<KeywordMoviesOutput>;

// The operation
/**
 * Movies
 */
export type KeywordMoviesError = TmdbOpError;
export const keywordMovies: API.OperationMethod<
  KeywordMoviesInput,
  KeywordMoviesOutput,
  KeywordMoviesError,
  TmdbOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: KeywordMoviesInput,
  output: KeywordMoviesOutput,
  errors: [] as const,
  protocol: TmdbProtocol,
  retry: Retry.Retry,
}));
