// Generated by @kevinmichaelchen/distilled. Do not edit by hand.
import * as S from "@kevinmichaelchen/distilled/schema";
import * as API from "@kevinmichaelchen/distilled/api";
import * as T from "../traits.ts";
import * as Retry from "../retry.ts";
import { TmdbProtocol, type TmdbOpError, type TmdbOpContext } from "../protocol.ts";

// Input Schema
export interface ListAddMovieInput { list_id: number; session_id: string; body?: { RAW_BODY?: string } }
export const ListAddMovieInput = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    list_id: S.Number.pipe(T.Label("list_id")),
    session_id: S.String.pipe(T.Query("session_id")),
    body: S.optional(S.Struct({
      RAW_BODY: S.optional(S.String),
    }).pipe(T.HttpBody())),
  }).pipe(T.Http({ method: "POST", uri: "/3/list/{list_id}/add_item", code: 200 }))
).annotate({ identifier: "ListAddMovieInput" }) as unknown as S.Codec<ListAddMovieInput>;

// Output Schema
export interface ListAddMovieOutput { status_code?: number; status_message?: string }
export const ListAddMovieOutput = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    status_code: S.optional(S.Number),
    status_message: S.optional(S.String),
  })
).annotate({ identifier: "ListAddMovieOutput" }) as unknown as S.Codec<ListAddMovieOutput>;

// The operation
/**
 * Add Movie
 *
 * Add a movie to a list.
 */
export type ListAddMovieError = TmdbOpError;
export const listAddMovie: API.OperationMethod<
  ListAddMovieInput,
  ListAddMovieOutput,
  ListAddMovieError,
  TmdbOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: ListAddMovieInput,
  output: ListAddMovieOutput,
  errors: [] as const,
  protocol: TmdbProtocol,
}));

// Input Schema
export interface ListCheckItemStatusInput { list_id: number; language?: string; movie_id?: number }
export const ListCheckItemStatusInput = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    list_id: S.Number.pipe(T.Label("list_id")),
    language: S.optional(S.String).pipe(T.Query("language")),
    movie_id: S.optional(S.Number).pipe(T.Query("movie_id")),
  }).pipe(T.Http({ method: "GET", uri: "/3/list/{list_id}/item_status", code: 200 }))
).annotate({ identifier: "ListCheckItemStatusInput" }) as unknown as S.Codec<ListCheckItemStatusInput>;

// Output Schema
export interface ListCheckItemStatusOutput { id?: number; item_present?: boolean }
export const ListCheckItemStatusOutput = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.optional(S.Number),
    item_present: S.optional(S.Boolean),
  })
).annotate({ identifier: "ListCheckItemStatusOutput" }) as unknown as S.Codec<ListCheckItemStatusOutput>;

// The operation
/**
 * Check Item Status
 *
 * Use this method to check if an item has already been added to the list.
 */
export type ListCheckItemStatusError = TmdbOpError;
export const listCheckItemStatus: API.OperationMethod<
  ListCheckItemStatusInput,
  ListCheckItemStatusOutput,
  ListCheckItemStatusError,
  TmdbOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: ListCheckItemStatusInput,
  output: ListCheckItemStatusOutput,
  errors: [] as const,
  protocol: TmdbProtocol,
  retry: Retry.Retry,
}));

// Input Schema
export interface ListClearInput { list_id: number; session_id: string; confirm: boolean }
export const ListClearInput = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    list_id: S.Number.pipe(T.Label("list_id")),
    session_id: S.String.pipe(T.Query("session_id")),
    confirm: S.Boolean.pipe(T.Query("confirm")),
  }).pipe(T.Http({ method: "POST", uri: "/3/list/{list_id}/clear", code: 200 }))
).annotate({ identifier: "ListClearInput" }) as unknown as S.Codec<ListClearInput>;

// Output Schema
export interface ListClearOutput { status_code?: number; status_message?: string }
export const ListClearOutput = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    status_code: S.optional(S.Number),
    status_message: S.optional(S.String),
  })
).annotate({ identifier: "ListClearOutput" }) as unknown as S.Codec<ListClearOutput>;

// The operation
/**
 * Clear
 *
 * Clear all items from a list.
 */
export type ListClearError = TmdbOpError;
export const listClear: API.OperationMethod<
  ListClearInput,
  ListClearOutput,
  ListClearError,
  TmdbOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: ListClearInput,
  output: ListClearOutput,
  errors: [] as const,
  protocol: TmdbProtocol,
}));

// Input Schema
export interface ListCreateInput { session_id: string; body?: { RAW_BODY: string } }
export const ListCreateInput = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    session_id: S.String.pipe(T.Query("session_id")),
    body: S.optional(S.Struct({
      RAW_BODY: S.String,
    }).pipe(T.HttpBody())),
  }).pipe(T.Http({ method: "POST", uri: "/3/list", code: 200 }))
).annotate({ identifier: "ListCreateInput" }) as unknown as S.Codec<ListCreateInput>;

// Output Schema
export interface ListCreateOutput { status_message?: string; success?: boolean; status_code?: number; list_id?: number }
export const ListCreateOutput = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    status_message: S.optional(S.String),
    success: S.optional(S.Boolean),
    status_code: S.optional(S.Number),
    list_id: S.optional(S.Number),
  })
).annotate({ identifier: "ListCreateOutput" }) as unknown as S.Codec<ListCreateOutput>;

// The operation
/**
 * Create
 */
export type ListCreateError = TmdbOpError;
export const listCreate: API.OperationMethod<
  ListCreateInput,
  ListCreateOutput,
  ListCreateError,
  TmdbOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: ListCreateInput,
  output: ListCreateOutput,
  errors: [] as const,
  protocol: TmdbProtocol,
}));

// Input Schema
export interface ListDetailsInput { list_id: number; language?: string; page?: number }
export const ListDetailsInput = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    list_id: S.Number.pipe(T.Label("list_id")),
    language: S.optional(S.String).pipe(T.Query("language")),
    page: S.optional(S.Number).pipe(T.Query("page")),
  }).pipe(T.Http({ method: "GET", uri: "/3/list/{list_id}", code: 200 }))
).annotate({ identifier: "ListDetailsInput" }) as unknown as S.Codec<ListDetailsInput>;

// Output Schema
export interface ListDetailsOutput { created_by?: string; description?: string; favorite_count?: number; id?: string; items?: ReadonlyArray<{ adult?: boolean; backdrop_path?: string; genre_ids?: ReadonlyArray<number>; id?: number; media_type?: string; original_language?: string; original_title?: string; overview?: string; popularity?: number; poster_path?: string; release_date?: string; title?: string; video?: boolean; vote_average?: number; vote_count?: number }>; item_count?: number; iso_639_1?: string; name?: string; poster_path?: string }
export const ListDetailsOutput = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    created_by: S.optional(S.String),
    description: S.optional(S.String),
    favorite_count: S.optional(S.Number),
    id: S.optional(S.String),
    items: S.optional(S.Array(S.Struct({
      adult: S.optional(S.Boolean),
      backdrop_path: S.optional(S.String),
      genre_ids: S.optional(S.Array(S.Number)),
      id: S.optional(S.Number),
      media_type: S.optional(S.String),
      original_language: S.optional(S.String),
      original_title: S.optional(S.String),
      overview: S.optional(S.String),
      popularity: S.optional(S.Number),
      poster_path: S.optional(S.String),
      release_date: S.optional(S.String),
      title: S.optional(S.String),
      video: S.optional(S.Boolean),
      vote_average: S.optional(S.Number),
      vote_count: S.optional(S.Number),
    }))),
    item_count: S.optional(S.Number),
    iso_639_1: S.optional(S.String),
    name: S.optional(S.String),
    poster_path: S.optional(S.String),
  })
).annotate({ identifier: "ListDetailsOutput" }) as unknown as S.Codec<ListDetailsOutput>;

// The operation
/**
 * Details
 */
export type ListDetailsError = TmdbOpError;
export const listDetails: API.OperationMethod<
  ListDetailsInput,
  ListDetailsOutput,
  ListDetailsError,
  TmdbOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: ListDetailsInput,
  output: ListDetailsOutput,
  errors: [] as const,
  protocol: TmdbProtocol,
  retry: Retry.Retry,
}));

// Input Schema
export interface ListDeleteInput { list_id: number; session_id: string }
export const ListDeleteInput = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    list_id: S.Number.pipe(T.Label("list_id")),
    session_id: S.String.pipe(T.Query("session_id")),
  }).pipe(T.Http({ method: "DELETE", uri: "/3/list/{list_id}", code: 200 }))
).annotate({ identifier: "ListDeleteInput" }) as unknown as S.Codec<ListDeleteInput>;

// Output Schema
export interface ListDeleteOutput { status_code?: number; status_message?: string }
export const ListDeleteOutput = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    status_code: S.optional(S.Number),
    status_message: S.optional(S.String),
  })
).annotate({ identifier: "ListDeleteOutput" }) as unknown as S.Codec<ListDeleteOutput>;

// The operation
/**
 * Delete
 *
 * Delete a list.
 */
export type ListDeleteError = TmdbOpError;
export const listDelete: API.OperationMethod<
  ListDeleteInput,
  ListDeleteOutput,
  ListDeleteError,
  TmdbOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: ListDeleteInput,
  output: ListDeleteOutput,
  errors: [] as const,
  protocol: TmdbProtocol,
}));

// Input Schema
export interface ListRemoveMovieInput { list_id: number; session_id: string; body?: { RAW_BODY: string } }
export const ListRemoveMovieInput = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    list_id: S.Number.pipe(T.Label("list_id")),
    session_id: S.String.pipe(T.Query("session_id")),
    body: S.optional(S.Struct({
      RAW_BODY: S.String,
    }).pipe(T.HttpBody())),
  }).pipe(T.Http({ method: "POST", uri: "/3/list/{list_id}/remove_item", code: 200 }))
).annotate({ identifier: "ListRemoveMovieInput" }) as unknown as S.Codec<ListRemoveMovieInput>;

// Output Schema
export interface ListRemoveMovieOutput { status_code?: number; status_message?: string }
export const ListRemoveMovieOutput = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    status_code: S.optional(S.Number),
    status_message: S.optional(S.String),
  })
).annotate({ identifier: "ListRemoveMovieOutput" }) as unknown as S.Codec<ListRemoveMovieOutput>;

// The operation
/**
 * Remove Movie
 *
 * Remove a movie from a list.
 */
export type ListRemoveMovieError = TmdbOpError;
export const listRemoveMovie: API.OperationMethod<
  ListRemoveMovieInput,
  ListRemoveMovieOutput,
  ListRemoveMovieError,
  TmdbOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: ListRemoveMovieInput,
  output: ListRemoveMovieOutput,
  errors: [] as const,
  protocol: TmdbProtocol,
}));
