// Generated by @kevinmichaelchen/distilled. Do not edit by hand.
import * as S from "@kevinmichaelchen/distilled/schema";
import * as API from "@kevinmichaelchen/distilled/api";
import * as T from "../traits.ts";
import * as Retry from "../retry.ts";
import { TmdbProtocol, type TmdbOpError, type TmdbOpContext } from "../protocol.ts";

// Input Schema
export interface NetworkDetailsInput { network_id: number }
export const NetworkDetailsInput = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    network_id: S.Number.pipe(T.Label("network_id")),
  }).pipe(T.Http({ method: "GET", uri: "/3/network/{network_id}", code: 200 }))
).annotate({ identifier: "NetworkDetailsInput" }) as unknown as S.Codec<NetworkDetailsInput>;

// Output Schema
export interface NetworkDetailsOutput { headquarters?: string; homepage?: string; id?: number; logo_path?: string; name?: string; origin_country?: string }
export const NetworkDetailsOutput = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    headquarters: S.optional(S.String),
    homepage: S.optional(S.String),
    id: S.optional(S.Number),
    logo_path: S.optional(S.String),
    name: S.optional(S.String),
    origin_country: S.optional(S.String),
  })
).annotate({ identifier: "NetworkDetailsOutput" }) as unknown as S.Codec<NetworkDetailsOutput>;

// The operation
/**
 * Details
 */
export type NetworkDetailsError = TmdbOpError;
export const networkDetails: API.OperationMethod<
  NetworkDetailsInput,
  NetworkDetailsOutput,
  NetworkDetailsError,
  TmdbOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: NetworkDetailsInput,
  output: NetworkDetailsOutput,
  errors: [] as const,
  protocol: TmdbProtocol,
  retry: Retry.Retry,
}));

// Input Schema
export interface DetailsCopyInput { network_id: number }
export const DetailsCopyInput = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    network_id: S.Number.pipe(T.Label("network_id")),
  }).pipe(T.Http({ method: "GET", uri: "/3/network/{network_id}/alternative_names", code: 200 }))
).annotate({ identifier: "DetailsCopyInput" }) as unknown as S.Codec<DetailsCopyInput>;

// Output Schema
export interface DetailsCopyOutput { id?: number; results?: ReadonlyArray<{ name?: string; type?: string }> }
export const DetailsCopyOutput = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.optional(S.Number),
    results: S.optional(S.Array(S.Struct({
      name: S.optional(S.String),
      type: S.optional(S.String),
    }))),
  })
).annotate({ identifier: "DetailsCopyOutput" }) as unknown as S.Codec<DetailsCopyOutput>;

// The operation
/**
 * Alternative Names
 *
 * Get the alternative names of a network.
 */
export type DetailsCopyError = TmdbOpError;
export const detailsCopy: API.OperationMethod<
  DetailsCopyInput,
  DetailsCopyOutput,
  DetailsCopyError,
  TmdbOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: DetailsCopyInput,
  output: DetailsCopyOutput,
  errors: [] as const,
  protocol: TmdbProtocol,
  retry: Retry.Retry,
}));

// Input Schema
export interface AlternativeNamesCopyInput { network_id: number }
export const AlternativeNamesCopyInput = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    network_id: S.Number.pipe(T.Label("network_id")),
  }).pipe(T.Http({ method: "GET", uri: "/3/network/{network_id}/images", code: 200 }))
).annotate({ identifier: "AlternativeNamesCopyInput" }) as unknown as S.Codec<AlternativeNamesCopyInput>;

// Output Schema
export interface AlternativeNamesCopyOutput { id?: number; logos?: ReadonlyArray<{ aspect_ratio?: number; file_path?: string; height?: number; id?: string; file_type?: string; vote_average?: number; vote_count?: number; width?: number }> }
export const AlternativeNamesCopyOutput = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.optional(S.Number),
    logos: S.optional(S.Array(S.Struct({
      aspect_ratio: S.optional(S.Number),
      file_path: S.optional(S.String),
      height: S.optional(S.Number),
      id: S.optional(S.String),
      file_type: S.optional(S.String),
      vote_average: S.optional(S.Number),
      vote_count: S.optional(S.Number),
      width: S.optional(S.Number),
    }))),
  })
).annotate({ identifier: "AlternativeNamesCopyOutput" }) as unknown as S.Codec<AlternativeNamesCopyOutput>;

// The operation
/**
 * Images
 *
 * Get the TV network logos by id.
 */
export type AlternativeNamesCopyError = TmdbOpError;
export const alternativeNamesCopy: API.OperationMethod<
  AlternativeNamesCopyInput,
  AlternativeNamesCopyOutput,
  AlternativeNamesCopyError,
  TmdbOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: AlternativeNamesCopyInput,
  output: AlternativeNamesCopyOutput,
  errors: [] as const,
  protocol: TmdbProtocol,
  retry: Retry.Retry,
}));
