// Generated by @kevinmichaelchen/distilled. Do not edit by hand.
import * as S from "@kevinmichaelchen/distilled/schema";
import * as API from "@kevinmichaelchen/distilled/api";
import * as T from "../traits.ts";
import * as Retry from "../retry.ts";
import { TmdbProtocol, type TmdbOpError, type TmdbOpContext } from "../protocol.ts";

// Input Schema
export interface ChangesPeopleListInput { end_date?: string; page?: number; start_date?: string }
export const ChangesPeopleListInput = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    end_date: S.optional(S.String).pipe(T.Query("end_date")),
    page: S.optional(S.Number).pipe(T.Query("page")),
    start_date: S.optional(S.String).pipe(T.Query("start_date")),
  }).pipe(T.Http({ method: "GET", uri: "/3/person/changes", code: 200 }))
).annotate({ identifier: "ChangesPeopleListInput" }) as unknown as S.Codec<ChangesPeopleListInput>;

// Output Schema
export interface ChangesPeopleListOutput { results?: ReadonlyArray<{ id?: number; adult?: boolean }>; page?: number; total_pages?: number; total_results?: number }
export const ChangesPeopleListOutput = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    results: S.optional(S.Array(S.Struct({
      id: S.optional(S.Number),
      adult: S.optional(S.Boolean),
    }))),
    page: S.optional(S.Number),
    total_pages: S.optional(S.Number),
    total_results: S.optional(S.Number),
  })
).annotate({ identifier: "ChangesPeopleListOutput" }) as unknown as S.Codec<ChangesPeopleListOutput>;

// The operation
/**
 * People List
 */
export type ChangesPeopleListError = TmdbOpError;
export const changesPeopleList: API.OperationMethod<
  ChangesPeopleListInput,
  ChangesPeopleListOutput,
  ChangesPeopleListError,
  TmdbOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: ChangesPeopleListInput,
  output: ChangesPeopleListOutput,
  errors: [] as const,
  protocol: TmdbProtocol,
  retry: Retry.Retry,
}));

// Input Schema
export interface PersonPopularListInput { language?: string; page?: number }
export const PersonPopularListInput = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    language: S.optional(S.String).pipe(T.Query("language")),
    page: S.optional(S.Number).pipe(T.Query("page")),
  }).pipe(T.Http({ method: "GET", uri: "/3/person/popular", code: 200 }))
).annotate({ identifier: "PersonPopularListInput" }) as unknown as S.Codec<PersonPopularListInput>;

// Output Schema
export interface PersonPopularListOutput { page?: number; results?: ReadonlyArray<{ adult?: boolean; gender?: number; id?: number; known_for?: ReadonlyArray<{ adult?: boolean; backdrop_path?: string; genre_ids?: ReadonlyArray<number>; id?: number; media_type?: string; original_language?: string; original_title?: string; overview?: string; poster_path?: string; release_date?: string; title?: string; video?: boolean; vote_average?: number; vote_count?: number }>; known_for_department?: string; name?: string; popularity?: number; profile_path?: string }>; total_pages?: number; total_results?: number }
export const PersonPopularListOutput = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    page: S.optional(S.Number),
    results: S.optional(S.Array(S.Struct({
      adult: S.optional(S.Boolean),
      gender: S.optional(S.Number),
      id: S.optional(S.Number),
      known_for: S.optional(S.Array(S.Struct({
        adult: S.optional(S.Boolean),
        backdrop_path: S.optional(S.String),
        genre_ids: S.optional(S.Array(S.Number)),
        id: S.optional(S.Number),
        media_type: S.optional(S.String),
        original_language: S.optional(S.String),
        original_title: S.optional(S.String),
        overview: S.optional(S.String),
        poster_path: S.optional(S.String),
        release_date: S.optional(S.String),
        title: S.optional(S.String),
        video: S.optional(S.Boolean),
        vote_average: S.optional(S.Number),
        vote_count: S.optional(S.Number),
      }))),
      known_for_department: S.optional(S.String),
      name: S.optional(S.String),
      popularity: S.optional(S.Number),
      profile_path: S.optional(S.String),
    }))),
    total_pages: S.optional(S.Number),
    total_results: S.optional(S.Number),
  })
).annotate({ identifier: "PersonPopularListOutput" }) as unknown as S.Codec<PersonPopularListOutput>;

// The operation
/**
 * Popular
 *
 * Get a list of people ordered by popularity.
 */
export type PersonPopularListError = TmdbOpError;
export const personPopularList: API.OperationMethod<
  PersonPopularListInput,
  PersonPopularListOutput,
  PersonPopularListError,
  TmdbOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: PersonPopularListInput,
  output: PersonPopularListOutput,
  errors: [] as const,
  protocol: TmdbProtocol,
  retry: Retry.Retry,
}));

// Input Schema
export interface PersonDetailsInput { person_id: number; append_to_response?: string; language?: string }
export const PersonDetailsInput = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    person_id: S.Number.pipe(T.Label("person_id")),
    append_to_response: S.optional(S.String).pipe(T.Query("append_to_response")),
    language: S.optional(S.String).pipe(T.Query("language")),
  }).pipe(T.Http({ method: "GET", uri: "/3/person/{person_id}", code: 200 }))
).annotate({ identifier: "PersonDetailsInput" }) as unknown as S.Codec<PersonDetailsInput>;

// Output Schema
export interface PersonDetailsOutput { adult?: boolean; also_known_as?: ReadonlyArray<string>; biography?: string; birthday?: string; deathday?: unknown; gender?: number; homepage?: unknown; id?: number; imdb_id?: string; known_for_department?: string; name?: string; place_of_birth?: string; popularity?: number; profile_path?: string }
export const PersonDetailsOutput = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    adult: S.optional(S.Boolean),
    also_known_as: S.optional(S.Array(S.String)),
    biography: S.optional(S.String),
    birthday: S.optional(S.String),
    deathday: S.optional(S.Unknown),
    gender: S.optional(S.Number),
    homepage: S.optional(S.Unknown),
    id: S.optional(S.Number),
    imdb_id: S.optional(S.String),
    known_for_department: S.optional(S.String),
    name: S.optional(S.String),
    place_of_birth: S.optional(S.String),
    popularity: S.optional(S.Number),
    profile_path: S.optional(S.String),
  })
).annotate({ identifier: "PersonDetailsOutput" }) as unknown as S.Codec<PersonDetailsOutput>;

// The operation
/**
 * Details
 *
 * Query the top level details of a person.
 *
 * @param append_to_response - comma separated list of endpoints within this namespace, 20 items max
 */
export type PersonDetailsError = TmdbOpError;
export const personDetails: API.OperationMethod<
  PersonDetailsInput,
  PersonDetailsOutput,
  PersonDetailsError,
  TmdbOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: PersonDetailsInput,
  output: PersonDetailsOutput,
  errors: [] as const,
  protocol: TmdbProtocol,
  retry: Retry.Retry,
}));

// Input Schema
export interface PersonChangesInput { person_id: number; end_date?: string; page?: number; start_date?: string }
export const PersonChangesInput = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    person_id: S.Number.pipe(T.Label("person_id")),
    end_date: S.optional(S.String).pipe(T.Query("end_date")),
    page: S.optional(S.Number).pipe(T.Query("page")),
    start_date: S.optional(S.String).pipe(T.Query("start_date")),
  }).pipe(T.Http({ method: "GET", uri: "/3/person/{person_id}/changes", code: 200 }))
).annotate({ identifier: "PersonChangesInput" }) as unknown as S.Codec<PersonChangesInput>;

// Output Schema
export interface PersonChangesOutput { changes?: ReadonlyArray<{ key?: string; items?: ReadonlyArray<{ id?: string; action?: string; time?: string; iso_639_1?: string; iso_3166_1?: string; value?: string }> }> }
export const PersonChangesOutput = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    changes: S.optional(S.Array(S.Struct({
      key: S.optional(S.String),
      items: S.optional(S.Array(S.Struct({
        id: S.optional(S.String),
        action: S.optional(S.String),
        time: S.optional(S.String),
        iso_639_1: S.optional(S.String),
        iso_3166_1: S.optional(S.String),
        value: S.optional(S.String),
      }))),
    }))),
  })
).annotate({ identifier: "PersonChangesOutput" }) as unknown as S.Codec<PersonChangesOutput>;

// The operation
/**
 * Changes
 *
 * Get the recent changes for a person.
 */
export type PersonChangesError = TmdbOpError;
export const personChanges: API.OperationMethod<
  PersonChangesInput,
  PersonChangesOutput,
  PersonChangesError,
  TmdbOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: PersonChangesInput,
  output: PersonChangesOutput,
  errors: [] as const,
  protocol: TmdbProtocol,
  retry: Retry.Retry,
}));

// Input Schema
export interface PersonCombinedCreditsInput { person_id: string; language?: string }
export const PersonCombinedCreditsInput = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    person_id: S.String.pipe(T.Label("person_id")),
    language: S.optional(S.String).pipe(T.Query("language")),
  }).pipe(T.Http({ method: "GET", uri: "/3/person/{person_id}/combined_credits", code: 200 }))
).annotate({ identifier: "PersonCombinedCreditsInput" }) as unknown as S.Codec<PersonCombinedCreditsInput>;

// Output Schema
export interface PersonCombinedCreditsOutput { cast?: ReadonlyArray<{ adult?: boolean; backdrop_path?: string; genre_ids?: ReadonlyArray<number>; id?: number; original_language?: string; original_title?: string; overview?: string; popularity?: number; poster_path?: string; release_date?: string; title?: string; video?: boolean; vote_average?: number; vote_count?: number; character?: string; credit_id?: string; order?: number; media_type?: string }>; crew?: ReadonlyArray<{ adult?: boolean; backdrop_path?: string; genre_ids?: ReadonlyArray<number>; id?: number; original_language?: string; original_title?: string; overview?: string; popularity?: number; poster_path?: string; release_date?: string; title?: string; video?: boolean; vote_average?: number; vote_count?: number; credit_id?: string; department?: string; job?: string; media_type?: string }>; id?: number }
export const PersonCombinedCreditsOutput = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    cast: S.optional(S.Array(S.Struct({
      adult: S.optional(S.Boolean),
      backdrop_path: S.optional(S.String),
      genre_ids: S.optional(S.Array(S.Number)),
      id: S.optional(S.Number),
      original_language: S.optional(S.String),
      original_title: S.optional(S.String),
      overview: S.optional(S.String),
      popularity: S.optional(S.Number),
      poster_path: S.optional(S.String),
      release_date: S.optional(S.String),
      title: S.optional(S.String),
      video: S.optional(S.Boolean),
      vote_average: S.optional(S.Number),
      vote_count: S.optional(S.Number),
      character: S.optional(S.String),
      credit_id: S.optional(S.String),
      order: S.optional(S.Number),
      media_type: S.optional(S.String),
    }))),
    crew: S.optional(S.Array(S.Struct({
      adult: S.optional(S.Boolean),
      backdrop_path: S.optional(S.String),
      genre_ids: S.optional(S.Array(S.Number)),
      id: S.optional(S.Number),
      original_language: S.optional(S.String),
      original_title: S.optional(S.String),
      overview: S.optional(S.String),
      popularity: S.optional(S.Number),
      poster_path: S.optional(S.String),
      release_date: S.optional(S.String),
      title: S.optional(S.String),
      video: S.optional(S.Boolean),
      vote_average: S.optional(S.Number),
      vote_count: S.optional(S.Number),
      credit_id: S.optional(S.String),
      department: S.optional(S.String),
      job: S.optional(S.String),
      media_type: S.optional(S.String),
    }))),
    id: S.optional(S.Number),
  })
).annotate({ identifier: "PersonCombinedCreditsOutput" }) as unknown as S.Codec<PersonCombinedCreditsOutput>;

// The operation
/**
 * Combined Credits
 *
 * Get the combined movie and TV credits that belong to a person.
 */
export type PersonCombinedCreditsError = TmdbOpError;
export const personCombinedCredits: API.OperationMethod<
  PersonCombinedCreditsInput,
  PersonCombinedCreditsOutput,
  PersonCombinedCreditsError,
  TmdbOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: PersonCombinedCreditsInput,
  output: PersonCombinedCreditsOutput,
  errors: [] as const,
  protocol: TmdbProtocol,
  retry: Retry.Retry,
}));

// Input Schema
export interface PersonExternalIdsInput { person_id: number }
export const PersonExternalIdsInput = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    person_id: S.Number.pipe(T.Label("person_id")),
  }).pipe(T.Http({ method: "GET", uri: "/3/person/{person_id}/external_ids", code: 200 }))
).annotate({ identifier: "PersonExternalIdsInput" }) as unknown as S.Codec<PersonExternalIdsInput>;

// Output Schema
export interface PersonExternalIdsOutput { id?: number; freebase_mid?: string; freebase_id?: string; imdb_id?: string; tvrage_id?: number; wikidata_id?: string; facebook_id?: string; instagram_id?: string; tiktok_id?: string; twitter_id?: string; youtube_id?: unknown }
export const PersonExternalIdsOutput = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.optional(S.Number),
    freebase_mid: S.optional(S.String),
    freebase_id: S.optional(S.String),
    imdb_id: S.optional(S.String),
    tvrage_id: S.optional(S.Number),
    wikidata_id: S.optional(S.String),
    facebook_id: S.optional(S.String),
    instagram_id: S.optional(S.String),
    tiktok_id: S.optional(S.String),
    twitter_id: S.optional(S.String),
    youtube_id: S.optional(S.Unknown),
  })
).annotate({ identifier: "PersonExternalIdsOutput" }) as unknown as S.Codec<PersonExternalIdsOutput>;

// The operation
/**
 * External IDs
 *
 * Get the external ID's that belong to a person.
 */
export type PersonExternalIdsError = TmdbOpError;
export const personExternalIds: API.OperationMethod<
  PersonExternalIdsInput,
  PersonExternalIdsOutput,
  PersonExternalIdsError,
  TmdbOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: PersonExternalIdsInput,
  output: PersonExternalIdsOutput,
  errors: [] as const,
  protocol: TmdbProtocol,
  retry: Retry.Retry,
}));

// Input Schema
export interface PersonImagesInput { person_id: number }
export const PersonImagesInput = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    person_id: S.Number.pipe(T.Label("person_id")),
  }).pipe(T.Http({ method: "GET", uri: "/3/person/{person_id}/images", code: 200 }))
).annotate({ identifier: "PersonImagesInput" }) as unknown as S.Codec<PersonImagesInput>;

// Output Schema
export interface PersonImagesOutput { id?: number; profiles?: ReadonlyArray<{ aspect_ratio?: number; height?: number; iso_639_1?: unknown; file_path?: string; vote_average?: number; vote_count?: number; width?: number }> }
export const PersonImagesOutput = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.optional(S.Number),
    profiles: S.optional(S.Array(S.Struct({
      aspect_ratio: S.optional(S.Number),
      height: S.optional(S.Number),
      iso_639_1: S.optional(S.Unknown),
      file_path: S.optional(S.String),
      vote_average: S.optional(S.Number),
      vote_count: S.optional(S.Number),
      width: S.optional(S.Number),
    }))),
  })
).annotate({ identifier: "PersonImagesOutput" }) as unknown as S.Codec<PersonImagesOutput>;

// The operation
/**
 * Images
 *
 * Get the profile images that belong to a person.
 */
export type PersonImagesError = TmdbOpError;
export const personImages: API.OperationMethod<
  PersonImagesInput,
  PersonImagesOutput,
  PersonImagesError,
  TmdbOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: PersonImagesInput,
  output: PersonImagesOutput,
  errors: [] as const,
  protocol: TmdbProtocol,
  retry: Retry.Retry,
}));

// Input Schema
export interface PersonLatestIdInput {  }
export const PersonLatestIdInput = /*@__PURE__*/ S.suspend(() =>
  S.Struct({

  }).pipe(T.Http({ method: "GET", uri: "/3/person/latest", code: 200 }))
).annotate({ identifier: "PersonLatestIdInput" }) as unknown as S.Codec<PersonLatestIdInput>;

// Output Schema
export interface PersonLatestIdOutput { adult?: boolean; also_known_as?: ReadonlyArray<unknown>; biography?: string; birthday?: unknown; deathday?: unknown; gender?: number; homepage?: unknown; id?: number; imdb_id?: unknown; known_for_department?: unknown; name?: string; place_of_birth?: unknown; popularity?: number; profile_path?: unknown }
export const PersonLatestIdOutput = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    adult: S.optional(S.Boolean),
    also_known_as: S.optional(S.Array(S.Unknown)),
    biography: S.optional(S.String),
    birthday: S.optional(S.Unknown),
    deathday: S.optional(S.Unknown),
    gender: S.optional(S.Number),
    homepage: S.optional(S.Unknown),
    id: S.optional(S.Number),
    imdb_id: S.optional(S.Unknown),
    known_for_department: S.optional(S.Unknown),
    name: S.optional(S.String),
    place_of_birth: S.optional(S.Unknown),
    popularity: S.optional(S.Number),
    profile_path: S.optional(S.Unknown),
  })
).annotate({ identifier: "PersonLatestIdOutput" }) as unknown as S.Codec<PersonLatestIdOutput>;

// The operation
/**
 * Latest
 *
 * Get the newest created person. This is a live response and will continuously change.
 */
export type PersonLatestIdError = TmdbOpError;
export const personLatestId: API.OperationMethod<
  PersonLatestIdInput,
  PersonLatestIdOutput,
  PersonLatestIdError,
  TmdbOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: PersonLatestIdInput,
  output: PersonLatestIdOutput,
  errors: [] as const,
  protocol: TmdbProtocol,
  retry: Retry.Retry,
}));

// Input Schema
export interface PersonMovieCreditsInput { person_id: number; language?: string }
export const PersonMovieCreditsInput = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    person_id: S.Number.pipe(T.Label("person_id")),
    language: S.optional(S.String).pipe(T.Query("language")),
  }).pipe(T.Http({ method: "GET", uri: "/3/person/{person_id}/movie_credits", code: 200 }))
).annotate({ identifier: "PersonMovieCreditsInput" }) as unknown as S.Codec<PersonMovieCreditsInput>;

// Output Schema
export interface PersonMovieCreditsOutput { cast?: ReadonlyArray<{ adult?: boolean; backdrop_path?: string; genre_ids?: ReadonlyArray<number>; id?: number; original_language?: string; original_title?: string; overview?: string; popularity?: number; poster_path?: string; release_date?: string; title?: string; video?: boolean; vote_average?: number; vote_count?: number; character?: string; credit_id?: string; order?: number }>; crew?: ReadonlyArray<{ adult?: boolean; backdrop_path?: string; genre_ids?: ReadonlyArray<number>; id?: number; original_language?: string; original_title?: string; overview?: string; popularity?: number; poster_path?: string; release_date?: string; title?: string; video?: boolean; vote_average?: number; vote_count?: number; credit_id?: string; department?: string; job?: string }>; id?: number }
export const PersonMovieCreditsOutput = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    cast: S.optional(S.Array(S.Struct({
      adult: S.optional(S.Boolean),
      backdrop_path: S.optional(S.String),
      genre_ids: S.optional(S.Array(S.Number)),
      id: S.optional(S.Number),
      original_language: S.optional(S.String),
      original_title: S.optional(S.String),
      overview: S.optional(S.String),
      popularity: S.optional(S.Number),
      poster_path: S.optional(S.String),
      release_date: S.optional(S.String),
      title: S.optional(S.String),
      video: S.optional(S.Boolean),
      vote_average: S.optional(S.Number),
      vote_count: S.optional(S.Number),
      character: S.optional(S.String),
      credit_id: S.optional(S.String),
      order: S.optional(S.Number),
    }))),
    crew: S.optional(S.Array(S.Struct({
      adult: S.optional(S.Boolean),
      backdrop_path: S.optional(S.String),
      genre_ids: S.optional(S.Array(S.Number)),
      id: S.optional(S.Number),
      original_language: S.optional(S.String),
      original_title: S.optional(S.String),
      overview: S.optional(S.String),
      popularity: S.optional(S.Number),
      poster_path: S.optional(S.String),
      release_date: S.optional(S.String),
      title: S.optional(S.String),
      video: S.optional(S.Boolean),
      vote_average: S.optional(S.Number),
      vote_count: S.optional(S.Number),
      credit_id: S.optional(S.String),
      department: S.optional(S.String),
      job: S.optional(S.String),
    }))),
    id: S.optional(S.Number),
  })
).annotate({ identifier: "PersonMovieCreditsOutput" }) as unknown as S.Codec<PersonMovieCreditsOutput>;

// The operation
/**
 * Movie Credits
 *
 * Get the movie credits for a person.
 */
export type PersonMovieCreditsError = TmdbOpError;
export const personMovieCredits: API.OperationMethod<
  PersonMovieCreditsInput,
  PersonMovieCreditsOutput,
  PersonMovieCreditsError,
  TmdbOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: PersonMovieCreditsInput,
  output: PersonMovieCreditsOutput,
  errors: [] as const,
  protocol: TmdbProtocol,
  retry: Retry.Retry,
}));

// Input Schema
export interface PersonTvCreditsInput { person_id: number; language?: string }
export const PersonTvCreditsInput = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    person_id: S.Number.pipe(T.Label("person_id")),
    language: S.optional(S.String).pipe(T.Query("language")),
  }).pipe(T.Http({ method: "GET", uri: "/3/person/{person_id}/tv_credits", code: 200 }))
).annotate({ identifier: "PersonTvCreditsInput" }) as unknown as S.Codec<PersonTvCreditsInput>;

// Output Schema
export interface PersonTvCreditsOutput { cast?: ReadonlyArray<{ adult?: boolean; backdrop_path?: string; genre_ids?: ReadonlyArray<number>; id?: number; origin_country?: ReadonlyArray<string>; original_language?: string; original_name?: string; overview?: string; popularity?: number; poster_path?: string; first_air_date?: string; name?: string; vote_average?: number; vote_count?: number; character?: string; credit_id?: string; episode_count?: number }>; crew?: ReadonlyArray<{ adult?: boolean; backdrop_path?: string; genre_ids?: ReadonlyArray<number>; id?: number; origin_country?: ReadonlyArray<string>; original_language?: string; original_name?: string; overview?: string; popularity?: number; poster_path?: string; first_air_date?: string; name?: string; vote_average?: number; vote_count?: number; credit_id?: string; department?: string; episode_count?: number; job?: string }>; id?: number }
export const PersonTvCreditsOutput = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    cast: S.optional(S.Array(S.Struct({
      adult: S.optional(S.Boolean),
      backdrop_path: S.optional(S.String),
      genre_ids: S.optional(S.Array(S.Number)),
      id: S.optional(S.Number),
      origin_country: S.optional(S.Array(S.String)),
      original_language: S.optional(S.String),
      original_name: S.optional(S.String),
      overview: S.optional(S.String),
      popularity: S.optional(S.Number),
      poster_path: S.optional(S.String),
      first_air_date: S.optional(S.String),
      name: S.optional(S.String),
      vote_average: S.optional(S.Number),
      vote_count: S.optional(S.Number),
      character: S.optional(S.String),
      credit_id: S.optional(S.String),
      episode_count: S.optional(S.Number),
    }))),
    crew: S.optional(S.Array(S.Struct({
      adult: S.optional(S.Boolean),
      backdrop_path: S.optional(S.String),
      genre_ids: S.optional(S.Array(S.Number)),
      id: S.optional(S.Number),
      origin_country: S.optional(S.Array(S.String)),
      original_language: S.optional(S.String),
      original_name: S.optional(S.String),
      overview: S.optional(S.String),
      popularity: S.optional(S.Number),
      poster_path: S.optional(S.String),
      first_air_date: S.optional(S.String),
      name: S.optional(S.String),
      vote_average: S.optional(S.Number),
      vote_count: S.optional(S.Number),
      credit_id: S.optional(S.String),
      department: S.optional(S.String),
      episode_count: S.optional(S.Number),
      job: S.optional(S.String),
    }))),
    id: S.optional(S.Number),
  })
).annotate({ identifier: "PersonTvCreditsOutput" }) as unknown as S.Codec<PersonTvCreditsOutput>;

// The operation
/**
 * TV Credits
 *
 * Get the TV credits that belong to a person.
 */
export type PersonTvCreditsError = TmdbOpError;
export const personTvCredits: API.OperationMethod<
  PersonTvCreditsInput,
  PersonTvCreditsOutput,
  PersonTvCreditsError,
  TmdbOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: PersonTvCreditsInput,
  output: PersonTvCreditsOutput,
  errors: [] as const,
  protocol: TmdbProtocol,
  retry: Retry.Retry,
}));

// Input Schema
export interface PersonTaggedImagesInput { person_id: number; page?: number }
export const PersonTaggedImagesInput = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    person_id: S.Number.pipe(T.Label("person_id")),
    page: S.optional(S.Number).pipe(T.Query("page")),
  }).pipe(T.Http({ method: "GET", uri: "/3/person/{person_id}/tagged_images", code: 200 }))
).annotate({ identifier: "PersonTaggedImagesInput" }) as unknown as S.Codec<PersonTaggedImagesInput>;

// Output Schema
export interface PersonTaggedImagesOutput { id?: number; page?: number; results?: ReadonlyArray<{ aspect_ratio?: number; file_path?: string; height?: number; id?: string; iso_639_1?: string; vote_average?: number; vote_count?: number; width?: number; image_type?: string; media?: { adult?: boolean; backdrop_path?: string; id?: number; title?: string; original_language?: string; original_title?: string; overview?: string; poster_path?: string; media_type?: string; genre_ids?: ReadonlyArray<number>; popularity?: number; release_date?: string; video?: boolean; vote_average?: number; vote_count?: number }; media_type?: string }>; total_pages?: number; total_results?: number }
export const PersonTaggedImagesOutput = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.optional(S.Number),
    page: S.optional(S.Number),
    results: S.optional(S.Array(S.Struct({
      aspect_ratio: S.optional(S.Number),
      file_path: S.optional(S.String),
      height: S.optional(S.Number),
      id: S.optional(S.String),
      iso_639_1: S.optional(S.String),
      vote_average: S.optional(S.Number),
      vote_count: S.optional(S.Number),
      width: S.optional(S.Number),
      image_type: S.optional(S.String),
      media: S.optional(S.Struct({
        adult: S.optional(S.Boolean),
        backdrop_path: S.optional(S.String),
        id: S.optional(S.Number),
        title: S.optional(S.String),
        original_language: S.optional(S.String),
        original_title: S.optional(S.String),
        overview: S.optional(S.String),
        poster_path: S.optional(S.String),
        media_type: S.optional(S.String),
        genre_ids: S.optional(S.Array(S.Number)),
        popularity: S.optional(S.Number),
        release_date: S.optional(S.String),
        video: S.optional(S.Boolean),
        vote_average: S.optional(S.Number),
        vote_count: S.optional(S.Number),
      })),
      media_type: S.optional(S.String),
    }))),
    total_pages: S.optional(S.Number),
    total_results: S.optional(S.Number),
  })
).annotate({ identifier: "PersonTaggedImagesOutput" }) as unknown as S.Codec<PersonTaggedImagesOutput>;

// The operation
/**
 * Tagged Images
 *
 * Get the tagged images for a person.
 */
export type PersonTaggedImagesError = TmdbOpError;
export const personTaggedImages: API.OperationMethod<
  PersonTaggedImagesInput,
  PersonTaggedImagesOutput,
  PersonTaggedImagesError,
  TmdbOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: PersonTaggedImagesInput,
  output: PersonTaggedImagesOutput,
  errors: [] as const,
  protocol: TmdbProtocol,
  retry: Retry.Retry,
}));

// Input Schema
export interface TranslationsInput { person_id: number }
export const TranslationsInput = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    person_id: S.Number.pipe(T.Label("person_id")),
  }).pipe(T.Http({ method: "GET", uri: "/3/person/{person_id}/translations", code: 200 }))
).annotate({ identifier: "TranslationsInput" }) as unknown as S.Codec<TranslationsInput>;

// Output Schema
export interface TranslationsOutput { id?: number; translations?: ReadonlyArray<{ iso_3166_1?: string; iso_639_1?: string; name?: string; english_name?: string; data?: { biography?: string; name?: string } }> }
export const TranslationsOutput = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.optional(S.Number),
    translations: S.optional(S.Array(S.Struct({
      iso_3166_1: S.optional(S.String),
      iso_639_1: S.optional(S.String),
      name: S.optional(S.String),
      english_name: S.optional(S.String),
      data: S.optional(S.Struct({
        biography: S.optional(S.String),
        name: S.optional(S.String),
      })),
    }))),
  })
).annotate({ identifier: "TranslationsOutput" }) as unknown as S.Codec<TranslationsOutput>;

// The operation
/**
 * Translations
 *
 * Get the translations that belong to a person.
 */
export type TranslationsError = TmdbOpError;
export const translations: API.OperationMethod<
  TranslationsInput,
  TranslationsOutput,
  TranslationsError,
  TmdbOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: TranslationsInput,
  output: TranslationsOutput,
  errors: [] as const,
  protocol: TmdbProtocol,
  retry: Retry.Retry,
}));
