// Generated by @kevinmichaelchen/distilled. Do not edit by hand.
import * as S from "@kevinmichaelchen/distilled/schema";
import * as API from "@kevinmichaelchen/distilled/api";
import * as T from "../traits.ts";
import * as Retry from "../retry.ts";
import { TmdbProtocol, type TmdbOpError, type TmdbOpContext } from "../protocol.ts";

// Input Schema
export interface ReviewDetailsInput { review_id: string }
export const ReviewDetailsInput = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    review_id: S.String.pipe(T.Label("review_id")),
  }).pipe(T.Http({ method: "GET", uri: "/3/review/{review_id}", code: 200 }))
).annotate({ identifier: "ReviewDetailsInput" }) as unknown as S.Codec<ReviewDetailsInput>;

// Output Schema
export interface ReviewDetailsOutput { id?: string; author?: string; author_details?: { name?: string; username?: string; avatar_path?: string; rating?: number }; content?: string; created_at?: string; iso_639_1?: string; media_id?: number; media_title?: string; media_type?: string; updated_at?: string; url?: string }
export const ReviewDetailsOutput = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.optional(S.String),
    author: S.optional(S.String),
    author_details: S.optional(S.Struct({
      name: S.optional(S.String),
      username: S.optional(S.String),
      avatar_path: S.optional(S.String),
      rating: S.optional(S.Number),
    })),
    content: S.optional(S.String),
    created_at: S.optional(S.String),
    iso_639_1: S.optional(S.String),
    media_id: S.optional(S.Number),
    media_title: S.optional(S.String),
    media_type: S.optional(S.String),
    updated_at: S.optional(S.String),
    url: S.optional(S.String),
  })
).annotate({ identifier: "ReviewDetailsOutput" }) as unknown as S.Codec<ReviewDetailsOutput>;

// The operation
/**
 * Details
 *
 * Retrieve the details of a movie or TV show review.
 */
export type ReviewDetailsError = TmdbOpError;
export const reviewDetails: API.OperationMethod<
  ReviewDetailsInput,
  ReviewDetailsOutput,
  ReviewDetailsError,
  TmdbOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: ReviewDetailsInput,
  output: ReviewDetailsOutput,
  errors: [] as const,
  protocol: TmdbProtocol,
  retry: Retry.Retry,
}));
