// Generated by @kevinmichaelchen/distilled. Do not edit by hand.
import * as S from "@kevinmichaelchen/distilled/schema";
import * as API from "@kevinmichaelchen/distilled/api";
import * as T from "../traits.ts";
import * as Retry from "../retry.ts";
import { TmdbProtocol, type TmdbOpError, type TmdbOpContext } from "../protocol.ts";

// Input Schema
export interface SearchCollectionInput { query: string; include_adult?: boolean; language?: string; page?: number; region?: string }
export const SearchCollectionInput = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    query: S.String.pipe(T.Query("query")),
    include_adult: S.optional(S.Boolean).pipe(T.Query("include_adult")),
    language: S.optional(S.String).pipe(T.Query("language")),
    page: S.optional(S.Number).pipe(T.Query("page")),
    region: S.optional(S.String).pipe(T.Query("region")),
  }).pipe(T.Http({ method: "GET", uri: "/3/search/collection", code: 200 }))
).annotate({ identifier: "SearchCollectionInput" }) as unknown as S.Codec<SearchCollectionInput>;

// Output Schema
export interface SearchCollectionOutput { page?: number; results?: ReadonlyArray<{ adult?: boolean; backdrop_path?: string; id?: number; name?: string; original_language?: string; original_name?: string; overview?: string; poster_path?: string }>; total_pages?: number; total_results?: number }
export const SearchCollectionOutput = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    page: S.optional(S.Number),
    results: S.optional(S.Array(S.Struct({
      adult: S.optional(S.Boolean),
      backdrop_path: S.optional(S.String),
      id: S.optional(S.Number),
      name: S.optional(S.String),
      original_language: S.optional(S.String),
      original_name: S.optional(S.String),
      overview: S.optional(S.String),
      poster_path: S.optional(S.String),
    }))),
    total_pages: S.optional(S.Number),
    total_results: S.optional(S.Number),
  })
).annotate({ identifier: "SearchCollectionOutput" }) as unknown as S.Codec<SearchCollectionOutput>;

// The operation
/**
 * Collection
 *
 * Search for collections by their original, translated and alternative names.
 */
export type SearchCollectionError = TmdbOpError;
export const searchCollection: API.OperationMethod<
  SearchCollectionInput,
  SearchCollectionOutput,
  SearchCollectionError,
  TmdbOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: SearchCollectionInput,
  output: SearchCollectionOutput,
  errors: [] as const,
  protocol: TmdbProtocol,
  retry: Retry.Retry,
}));

// Input Schema
export interface SearchCompanyInput { query: string; page?: number }
export const SearchCompanyInput = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    query: S.String.pipe(T.Query("query")),
    page: S.optional(S.Number).pipe(T.Query("page")),
  }).pipe(T.Http({ method: "GET", uri: "/3/search/company", code: 200 }))
).annotate({ identifier: "SearchCompanyInput" }) as unknown as S.Codec<SearchCompanyInput>;

// Output Schema
export interface SearchCompanyOutput { page?: number; results?: ReadonlyArray<{ id?: number; logo_path?: string; name?: string; origin_country?: string }>; total_pages?: number; total_results?: number }
export const SearchCompanyOutput = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    page: S.optional(S.Number),
    results: S.optional(S.Array(S.Struct({
      id: S.optional(S.Number),
      logo_path: S.optional(S.String),
      name: S.optional(S.String),
      origin_country: S.optional(S.String),
    }))),
    total_pages: S.optional(S.Number),
    total_results: S.optional(S.Number),
  })
).annotate({ identifier: "SearchCompanyOutput" }) as unknown as S.Codec<SearchCompanyOutput>;

// The operation
/**
 * Company
 *
 * Search for companies by their original and alternative names.
 */
export type SearchCompanyError = TmdbOpError;
export const searchCompany: API.OperationMethod<
  SearchCompanyInput,
  SearchCompanyOutput,
  SearchCompanyError,
  TmdbOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: SearchCompanyInput,
  output: SearchCompanyOutput,
  errors: [] as const,
  protocol: TmdbProtocol,
  retry: Retry.Retry,
}));

// Input Schema
export interface SearchKeywordInput { query: string; page?: number }
export const SearchKeywordInput = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    query: S.String.pipe(T.Query("query")),
    page: S.optional(S.Number).pipe(T.Query("page")),
  }).pipe(T.Http({ method: "GET", uri: "/3/search/keyword", code: 200 }))
).annotate({ identifier: "SearchKeywordInput" }) as unknown as S.Codec<SearchKeywordInput>;

// Output Schema
export interface SearchKeywordOutput { page?: number; results?: ReadonlyArray<{ id?: number; name?: string }>; total_pages?: number; total_results?: number }
export const SearchKeywordOutput = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    page: S.optional(S.Number),
    results: S.optional(S.Array(S.Struct({
      id: S.optional(S.Number),
      name: S.optional(S.String),
    }))),
    total_pages: S.optional(S.Number),
    total_results: S.optional(S.Number),
  })
).annotate({ identifier: "SearchKeywordOutput" }) as unknown as S.Codec<SearchKeywordOutput>;

// The operation
/**
 * Keyword
 *
 * Search for keywords by their name.
 */
export type SearchKeywordError = TmdbOpError;
export const searchKeyword: API.OperationMethod<
  SearchKeywordInput,
  SearchKeywordOutput,
  SearchKeywordError,
  TmdbOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: SearchKeywordInput,
  output: SearchKeywordOutput,
  errors: [] as const,
  protocol: TmdbProtocol,
  retry: Retry.Retry,
}));

// Input Schema
export interface SearchMovieInput { query: string; include_adult?: boolean; language?: string; primary_release_year?: string; page?: number; region?: string; year?: string }
export const SearchMovieInput = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    query: S.String.pipe(T.Query("query")),
    include_adult: S.optional(S.Boolean).pipe(T.Query("include_adult")),
    language: S.optional(S.String).pipe(T.Query("language")),
    primary_release_year: S.optional(S.String).pipe(T.Query("primary_release_year")),
    page: S.optional(S.Number).pipe(T.Query("page")),
    region: S.optional(S.String).pipe(T.Query("region")),
    year: S.optional(S.String).pipe(T.Query("year")),
  }).pipe(T.Http({ method: "GET", uri: "/3/search/movie", code: 200 }))
).annotate({ identifier: "SearchMovieInput" }) as unknown as S.Codec<SearchMovieInput>;

// Output Schema
export interface SearchMovieOutput { page?: number; results?: ReadonlyArray<{ adult?: boolean; backdrop_path?: string; genre_ids?: ReadonlyArray<number>; id?: number; original_language?: string; original_title?: string; overview?: string; popularity?: number; poster_path?: string; release_date?: string; title?: string; video?: boolean; vote_average?: number; vote_count?: number }>; total_pages?: number; total_results?: number }
export const SearchMovieOutput = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    page: S.optional(S.Number),
    results: S.optional(S.Array(S.Struct({
      adult: S.optional(S.Boolean),
      backdrop_path: S.optional(S.String),
      genre_ids: S.optional(S.Array(S.Number)),
      id: S.optional(S.Number),
      original_language: S.optional(S.String),
      original_title: S.optional(S.String),
      overview: S.optional(S.String),
      popularity: S.optional(S.Number),
      poster_path: S.optional(S.String),
      release_date: S.optional(S.String),
      title: S.optional(S.String),
      video: S.optional(S.Boolean),
      vote_average: S.optional(S.Number),
      vote_count: S.optional(S.Number),
    }))),
    total_pages: S.optional(S.Number),
    total_results: S.optional(S.Number),
  })
).annotate({ identifier: "SearchMovieOutput" }) as unknown as S.Codec<SearchMovieOutput>;

// The operation
/**
 * Movie
 *
 * Search for movies by their original, translated and alternative titles.
 */
export type SearchMovieError = TmdbOpError;
export const searchMovie: API.OperationMethod<
  SearchMovieInput,
  SearchMovieOutput,
  SearchMovieError,
  TmdbOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: SearchMovieInput,
  output: SearchMovieOutput,
  errors: [] as const,
  protocol: TmdbProtocol,
  retry: Retry.Retry,
}));

// Input Schema
export interface SearchMultiInput { query: string; include_adult?: boolean; language?: string; page?: number }
export const SearchMultiInput = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    query: S.String.pipe(T.Query("query")),
    include_adult: S.optional(S.Boolean).pipe(T.Query("include_adult")),
    language: S.optional(S.String).pipe(T.Query("language")),
    page: S.optional(S.Number).pipe(T.Query("page")),
  }).pipe(T.Http({ method: "GET", uri: "/3/search/multi", code: 200 }))
).annotate({ identifier: "SearchMultiInput" }) as unknown as S.Codec<SearchMultiInput>;

// Output Schema
export interface SearchMultiOutput { page?: number; results?: ReadonlyArray<{ adult?: boolean; backdrop_path?: string; id?: number; title?: string; original_language?: string; original_title?: string; overview?: string; poster_path?: string; media_type?: string; genre_ids?: ReadonlyArray<number>; popularity?: number; release_date?: string; video?: boolean; vote_average?: number; vote_count?: number; name?: string; original_name?: string }>; total_pages?: number; total_results?: number }
export const SearchMultiOutput = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    page: S.optional(S.Number),
    results: S.optional(S.Array(S.Struct({
      adult: S.optional(S.Boolean),
      backdrop_path: S.optional(S.String),
      id: S.optional(S.Number),
      title: S.optional(S.String),
      original_language: S.optional(S.String),
      original_title: S.optional(S.String),
      overview: S.optional(S.String),
      poster_path: S.optional(S.String),
      media_type: S.optional(S.String),
      genre_ids: S.optional(S.Array(S.Number)),
      popularity: S.optional(S.Number),
      release_date: S.optional(S.String),
      video: S.optional(S.Boolean),
      vote_average: S.optional(S.Number),
      vote_count: S.optional(S.Number),
      name: S.optional(S.String),
      original_name: S.optional(S.String),
    }))),
    total_pages: S.optional(S.Number),
    total_results: S.optional(S.Number),
  })
).annotate({ identifier: "SearchMultiOutput" }) as unknown as S.Codec<SearchMultiOutput>;

// The operation
/**
 * Multi
 *
 * Use multi search when you want to search for movies, TV shows and people in a single request.
 */
export type SearchMultiError = TmdbOpError;
export const searchMulti: API.OperationMethod<
  SearchMultiInput,
  SearchMultiOutput,
  SearchMultiError,
  TmdbOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: SearchMultiInput,
  output: SearchMultiOutput,
  errors: [] as const,
  protocol: TmdbProtocol,
  retry: Retry.Retry,
}));

// Input Schema
export interface SearchPersonInput { query: string; include_adult?: boolean; language?: string; page?: number }
export const SearchPersonInput = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    query: S.String.pipe(T.Query("query")),
    include_adult: S.optional(S.Boolean).pipe(T.Query("include_adult")),
    language: S.optional(S.String).pipe(T.Query("language")),
    page: S.optional(S.Number).pipe(T.Query("page")),
  }).pipe(T.Http({ method: "GET", uri: "/3/search/person", code: 200 }))
).annotate({ identifier: "SearchPersonInput" }) as unknown as S.Codec<SearchPersonInput>;

// Output Schema
export interface SearchPersonOutput { page?: number; results?: ReadonlyArray<{ adult?: boolean; gender?: number; id?: number; known_for_department?: string; name?: string; original_name?: string; popularity?: number; profile_path?: string; known_for?: ReadonlyArray<{ adult?: boolean; backdrop_path?: string; id?: number; title?: string; original_language?: string; original_title?: string; overview?: string; poster_path?: string; media_type?: string; genre_ids?: ReadonlyArray<number>; popularity?: number; release_date?: string; video?: boolean; vote_average?: number; vote_count?: number }> }>; total_pages?: number; total_results?: number }
export const SearchPersonOutput = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    page: S.optional(S.Number),
    results: S.optional(S.Array(S.Struct({
      adult: S.optional(S.Boolean),
      gender: S.optional(S.Number),
      id: S.optional(S.Number),
      known_for_department: S.optional(S.String),
      name: S.optional(S.String),
      original_name: S.optional(S.String),
      popularity: S.optional(S.Number),
      profile_path: S.optional(S.String),
      known_for: S.optional(S.Array(S.Struct({
        adult: S.optional(S.Boolean),
        backdrop_path: S.optional(S.String),
        id: S.optional(S.Number),
        title: S.optional(S.String),
        original_language: S.optional(S.String),
        original_title: S.optional(S.String),
        overview: S.optional(S.String),
        poster_path: S.optional(S.String),
        media_type: S.optional(S.String),
        genre_ids: S.optional(S.Array(S.Number)),
        popularity: S.optional(S.Number),
        release_date: S.optional(S.String),
        video: S.optional(S.Boolean),
        vote_average: S.optional(S.Number),
        vote_count: S.optional(S.Number),
      }))),
    }))),
    total_pages: S.optional(S.Number),
    total_results: S.optional(S.Number),
  })
).annotate({ identifier: "SearchPersonOutput" }) as unknown as S.Codec<SearchPersonOutput>;

// The operation
/**
 * Person
 *
 * Search for people by their name and also known as names.
 */
export type SearchPersonError = TmdbOpError;
export const searchPerson: API.OperationMethod<
  SearchPersonInput,
  SearchPersonOutput,
  SearchPersonError,
  TmdbOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: SearchPersonInput,
  output: SearchPersonOutput,
  errors: [] as const,
  protocol: TmdbProtocol,
  retry: Retry.Retry,
}));

// Input Schema
export interface SearchTvInput { query: string; first_air_date_year?: number; include_adult?: boolean; language?: string; page?: number; year?: number }
export const SearchTvInput = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    query: S.String.pipe(T.Query("query")),
    first_air_date_year: S.optional(S.Number).pipe(T.Query("first_air_date_year")),
    include_adult: S.optional(S.Boolean).pipe(T.Query("include_adult")),
    language: S.optional(S.String).pipe(T.Query("language")),
    page: S.optional(S.Number).pipe(T.Query("page")),
    year: S.optional(S.Number).pipe(T.Query("year")),
  }).pipe(T.Http({ method: "GET", uri: "/3/search/tv", code: 200 }))
).annotate({ identifier: "SearchTvInput" }) as unknown as S.Codec<SearchTvInput>;

// Output Schema
export interface SearchTvOutput { page?: number; results?: ReadonlyArray<{ adult?: boolean; backdrop_path?: string; genre_ids?: ReadonlyArray<number>; id?: number; origin_country?: ReadonlyArray<string>; original_language?: string; original_name?: string; overview?: string; popularity?: number; poster_path?: string; first_air_date?: string; name?: string; vote_average?: number; vote_count?: number }>; total_pages?: number; total_results?: number }
export const SearchTvOutput = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    page: S.optional(S.Number),
    results: S.optional(S.Array(S.Struct({
      adult: S.optional(S.Boolean),
      backdrop_path: S.optional(S.String),
      genre_ids: S.optional(S.Array(S.Number)),
      id: S.optional(S.Number),
      origin_country: S.optional(S.Array(S.String)),
      original_language: S.optional(S.String),
      original_name: S.optional(S.String),
      overview: S.optional(S.String),
      popularity: S.optional(S.Number),
      poster_path: S.optional(S.String),
      first_air_date: S.optional(S.String),
      name: S.optional(S.String),
      vote_average: S.optional(S.Number),
      vote_count: S.optional(S.Number),
    }))),
    total_pages: S.optional(S.Number),
    total_results: S.optional(S.Number),
  })
).annotate({ identifier: "SearchTvOutput" }) as unknown as S.Codec<SearchTvOutput>;

// The operation
/**
 * TV
 *
 * Search for TV shows by their original, translated and also known as names.
 *
 * @param first_air_date_year - Search only the first air date. Valid values are: 1000..9999
 * @param year - Search the first air date and all episode air dates. Valid values are: 1000..9999
 */
export type SearchTvError = TmdbOpError;
export const searchTv: API.OperationMethod<
  SearchTvInput,
  SearchTvOutput,
  SearchTvError,
  TmdbOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: SearchTvInput,
  output: SearchTvOutput,
  errors: [] as const,
  protocol: TmdbProtocol,
  retry: Retry.Retry,
}));
