// Generated by @kevinmichaelchen/distilled. Do not edit by hand.
import * as S from "@kevinmichaelchen/distilled/schema";
import * as API from "@kevinmichaelchen/distilled/api";
import * as T from "../traits.ts";
import * as Retry from "../retry.ts";
import { TmdbProtocol, type TmdbOpError, type TmdbOpContext } from "../protocol.ts";

// Input Schema
export interface TrendingAllInput { time_window: "day" | "week"; language?: string }
export const TrendingAllInput = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    time_window: S.Literals(["day", "week"]).pipe(T.Label("time_window")),
    language: S.optional(S.String).pipe(T.Query("language")),
  }).pipe(T.Http({ method: "GET", uri: "/3/trending/all/{time_window}", code: 200 }))
).annotate({ identifier: "TrendingAllInput" }) as unknown as S.Codec<TrendingAllInput>;

// Output Schema
export interface TrendingAllOutput { page?: number; results?: ReadonlyArray<{ adult?: boolean; backdrop_path?: string; id?: number; title?: string; original_language?: string; original_title?: string; overview?: string; poster_path?: string; media_type?: string; genre_ids?: ReadonlyArray<number>; popularity?: number; release_date?: string; video?: boolean; vote_average?: number; vote_count?: number }>; total_pages?: number; total_results?: number }
export const TrendingAllOutput = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    page: S.optional(S.Number),
    results: S.optional(S.Array(S.Struct({
      adult: S.optional(S.Boolean),
      backdrop_path: S.optional(S.String),
      id: S.optional(S.Number),
      title: S.optional(S.String),
      original_language: S.optional(S.String),
      original_title: S.optional(S.String),
      overview: S.optional(S.String),
      poster_path: S.optional(S.String),
      media_type: S.optional(S.String),
      genre_ids: S.optional(S.Array(S.Number)),
      popularity: S.optional(S.Number),
      release_date: S.optional(S.String),
      video: S.optional(S.Boolean),
      vote_average: S.optional(S.Number),
      vote_count: S.optional(S.Number),
    }))),
    total_pages: S.optional(S.Number),
    total_results: S.optional(S.Number),
  })
).annotate({ identifier: "TrendingAllOutput" }) as unknown as S.Codec<TrendingAllOutput>;

// The operation
/**
 * All
 *
 * Get the trending movies, TV shows and people.
 *
 * @param language - `ISO-639-1`-`ISO-3166-1` code
 */
export type TrendingAllError = TmdbOpError;
export const trendingAll: API.OperationMethod<
  TrendingAllInput,
  TrendingAllOutput,
  TrendingAllError,
  TmdbOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: TrendingAllInput,
  output: TrendingAllOutput,
  errors: [] as const,
  protocol: TmdbProtocol,
  retry: Retry.Retry,
}));

// Input Schema
export interface TrendingMoviesInput { time_window: "day" | "week"; language?: string }
export const TrendingMoviesInput = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    time_window: S.Literals(["day", "week"]).pipe(T.Label("time_window")),
    language: S.optional(S.String).pipe(T.Query("language")),
  }).pipe(T.Http({ method: "GET", uri: "/3/trending/movie/{time_window}", code: 200 }))
).annotate({ identifier: "TrendingMoviesInput" }) as unknown as S.Codec<TrendingMoviesInput>;

// Output Schema
export interface TrendingMoviesOutput { page?: number; results?: ReadonlyArray<{ adult?: boolean; backdrop_path?: string; id?: number; title?: string; original_language?: string; original_title?: string; overview?: string; poster_path?: string; media_type?: string; genre_ids?: ReadonlyArray<number>; popularity?: number; release_date?: string; video?: boolean; vote_average?: number; vote_count?: number }>; total_pages?: number; total_results?: number }
export const TrendingMoviesOutput = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    page: S.optional(S.Number),
    results: S.optional(S.Array(S.Struct({
      adult: S.optional(S.Boolean),
      backdrop_path: S.optional(S.String),
      id: S.optional(S.Number),
      title: S.optional(S.String),
      original_language: S.optional(S.String),
      original_title: S.optional(S.String),
      overview: S.optional(S.String),
      poster_path: S.optional(S.String),
      media_type: S.optional(S.String),
      genre_ids: S.optional(S.Array(S.Number)),
      popularity: S.optional(S.Number),
      release_date: S.optional(S.String),
      video: S.optional(S.Boolean),
      vote_average: S.optional(S.Number),
      vote_count: S.optional(S.Number),
    }))),
    total_pages: S.optional(S.Number),
    total_results: S.optional(S.Number),
  })
).annotate({ identifier: "TrendingMoviesOutput" }) as unknown as S.Codec<TrendingMoviesOutput>;

// The operation
/**
 * Movies
 *
 * Get the trending movies on TMDB.
 *
 * @param language - `ISO-639-1`-`ISO-3166-1` code
 */
export type TrendingMoviesError = TmdbOpError;
export const trendingMovies: API.OperationMethod<
  TrendingMoviesInput,
  TrendingMoviesOutput,
  TrendingMoviesError,
  TmdbOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: TrendingMoviesInput,
  output: TrendingMoviesOutput,
  errors: [] as const,
  protocol: TmdbProtocol,
  retry: Retry.Retry,
}));

// Input Schema
export interface TrendingPeopleInput { time_window: "day" | "week"; language?: string }
export const TrendingPeopleInput = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    time_window: S.Literals(["day", "week"]).pipe(T.Label("time_window")),
    language: S.optional(S.String).pipe(T.Query("language")),
  }).pipe(T.Http({ method: "GET", uri: "/3/trending/person/{time_window}", code: 200 }))
).annotate({ identifier: "TrendingPeopleInput" }) as unknown as S.Codec<TrendingPeopleInput>;

// Output Schema
export interface TrendingPeopleOutput { page?: number; results?: ReadonlyArray<{ adult?: boolean; id?: number; name?: string; original_name?: string; media_type?: string; popularity?: number; gender?: number; known_for_department?: string; profile_path?: string; known_for?: ReadonlyArray<{ adult?: boolean; backdrop_path?: string; id?: number; title?: string; original_language?: string; original_title?: string; overview?: string; poster_path?: string; media_type?: string; genre_ids?: ReadonlyArray<number>; popularity?: number; release_date?: string; video?: boolean; vote_average?: number; vote_count?: number }> }>; total_pages?: number; total_results?: number }
export const TrendingPeopleOutput = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    page: S.optional(S.Number),
    results: S.optional(S.Array(S.Struct({
      adult: S.optional(S.Boolean),
      id: S.optional(S.Number),
      name: S.optional(S.String),
      original_name: S.optional(S.String),
      media_type: S.optional(S.String),
      popularity: S.optional(S.Number),
      gender: S.optional(S.Number),
      known_for_department: S.optional(S.String),
      profile_path: S.optional(S.String),
      known_for: S.optional(S.Array(S.Struct({
        adult: S.optional(S.Boolean),
        backdrop_path: S.optional(S.String),
        id: S.optional(S.Number),
        title: S.optional(S.String),
        original_language: S.optional(S.String),
        original_title: S.optional(S.String),
        overview: S.optional(S.String),
        poster_path: S.optional(S.String),
        media_type: S.optional(S.String),
        genre_ids: S.optional(S.Array(S.Number)),
        popularity: S.optional(S.Number),
        release_date: S.optional(S.String),
        video: S.optional(S.Boolean),
        vote_average: S.optional(S.Number),
        vote_count: S.optional(S.Number),
      }))),
    }))),
    total_pages: S.optional(S.Number),
    total_results: S.optional(S.Number),
  })
).annotate({ identifier: "TrendingPeopleOutput" }) as unknown as S.Codec<TrendingPeopleOutput>;

// The operation
/**
 * People
 *
 * Get the trending people on TMDB.
 *
 * @param language - `ISO-639-1`-`ISO-3166-1` code
 */
export type TrendingPeopleError = TmdbOpError;
export const trendingPeople: API.OperationMethod<
  TrendingPeopleInput,
  TrendingPeopleOutput,
  TrendingPeopleError,
  TmdbOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: TrendingPeopleInput,
  output: TrendingPeopleOutput,
  errors: [] as const,
  protocol: TmdbProtocol,
  retry: Retry.Retry,
}));

// Input Schema
export interface TrendingTvInput { time_window: "day" | "week"; language?: string }
export const TrendingTvInput = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    time_window: S.Literals(["day", "week"]).pipe(T.Label("time_window")),
    language: S.optional(S.String).pipe(T.Query("language")),
  }).pipe(T.Http({ method: "GET", uri: "/3/trending/tv/{time_window}", code: 200 }))
).annotate({ identifier: "TrendingTvInput" }) as unknown as S.Codec<TrendingTvInput>;

// Output Schema
export interface TrendingTvOutput { page?: number; results?: ReadonlyArray<{ adult?: boolean; backdrop_path?: string; id?: number; name?: string; original_language?: string; original_name?: string; overview?: string; poster_path?: string; media_type?: string; genre_ids?: ReadonlyArray<number>; popularity?: number; first_air_date?: string; vote_average?: number; vote_count?: number; origin_country?: ReadonlyArray<string> }>; total_pages?: number; total_results?: number }
export const TrendingTvOutput = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    page: S.optional(S.Number),
    results: S.optional(S.Array(S.Struct({
      adult: S.optional(S.Boolean),
      backdrop_path: S.optional(S.String),
      id: S.optional(S.Number),
      name: S.optional(S.String),
      original_language: S.optional(S.String),
      original_name: S.optional(S.String),
      overview: S.optional(S.String),
      poster_path: S.optional(S.String),
      media_type: S.optional(S.String),
      genre_ids: S.optional(S.Array(S.Number)),
      popularity: S.optional(S.Number),
      first_air_date: S.optional(S.String),
      vote_average: S.optional(S.Number),
      vote_count: S.optional(S.Number),
      origin_country: S.optional(S.Array(S.String)),
    }))),
    total_pages: S.optional(S.Number),
    total_results: S.optional(S.Number),
  })
).annotate({ identifier: "TrendingTvOutput" }) as unknown as S.Codec<TrendingTvOutput>;

// The operation
/**
 * TV
 *
 * Get the trending TV shows on TMDB.
 *
 * @param language - `ISO-639-1`-`ISO-3166-1` code
 */
export type TrendingTvError = TmdbOpError;
export const trendingTv: API.OperationMethod<
  TrendingTvInput,
  TrendingTvOutput,
  TrendingTvError,
  TmdbOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: TrendingTvInput,
  output: TrendingTvOutput,
  errors: [] as const,
  protocol: TmdbProtocol,
  retry: Retry.Retry,
}));
