// Generated by @kevinmichaelchen/distilled. Do not edit by hand.
import * as S from "@kevinmichaelchen/distilled/schema";
import * as API from "@kevinmichaelchen/distilled/api";
import * as T from "../traits.ts";
import * as Retry from "../retry.ts";
import { TmdbProtocol, type TmdbOpError, type TmdbOpContext } from "../protocol.ts";

// Input Schema
export interface WatchProvidersAvailableRegionsInput { language?: string }
export const WatchProvidersAvailableRegionsInput = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    language: S.optional(S.String).pipe(T.Query("language")),
  }).pipe(T.Http({ method: "GET", uri: "/3/watch/providers/regions", code: 200 }))
).annotate({ identifier: "WatchProvidersAvailableRegionsInput" }) as unknown as S.Codec<WatchProvidersAvailableRegionsInput>;

// Output Schema
export interface WatchProvidersAvailableRegionsOutput { results?: ReadonlyArray<{ iso_3166_1?: string; english_name?: string; native_name?: string }> }
export const WatchProvidersAvailableRegionsOutput = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    results: S.optional(S.Array(S.Struct({
      iso_3166_1: S.optional(S.String),
      english_name: S.optional(S.String),
      native_name: S.optional(S.String),
    }))),
  })
).annotate({ identifier: "WatchProvidersAvailableRegionsOutput" }) as unknown as S.Codec<WatchProvidersAvailableRegionsOutput>;

// The operation
/**
 * Available Regions
 *
 * Get the list of the countries we have watch provider (OTT/streaming) data for.
 */
export type WatchProvidersAvailableRegionsError = TmdbOpError;
export const watchProvidersAvailableRegions: API.OperationMethod<
  WatchProvidersAvailableRegionsInput,
  WatchProvidersAvailableRegionsOutput,
  WatchProvidersAvailableRegionsError,
  TmdbOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: WatchProvidersAvailableRegionsInput,
  output: WatchProvidersAvailableRegionsOutput,
  errors: [] as const,
  protocol: TmdbProtocol,
  retry: Retry.Retry,
}));

// Input Schema
export interface WatchProvidersMovieListInput { language?: string; watch_region?: string }
export const WatchProvidersMovieListInput = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    language: S.optional(S.String).pipe(T.Query("language")),
    watch_region: S.optional(S.String).pipe(T.Query("watch_region")),
  }).pipe(T.Http({ method: "GET", uri: "/3/watch/providers/movie", code: 200 }))
).annotate({ identifier: "WatchProvidersMovieListInput" }) as unknown as S.Codec<WatchProvidersMovieListInput>;

// Output Schema
export interface WatchProvidersMovieListOutput { results?: ReadonlyArray<{ display_priorities?: { CA?: number; AE?: number; AR?: number; AT?: number; AU?: number; BE?: number; BO?: number; BR?: number; BG?: number; CH?: number; CL?: number; CO?: number; CR?: number; CZ?: number; DE?: number; DK?: number; EC?: number; EE?: number; EG?: number; ES?: number; FI?: number; FR?: number; GB?: number; GR?: number; GT?: number; HK?: number; HN?: number; HU?: number; ID?: number; IE?: number; IN?: number; IT?: number; JP?: number; LT?: number; LV?: number; MX?: number; MY?: number; NL?: number; NO?: number; NZ?: number; PE?: number; PH?: number; PL?: number; PT?: number; PY?: number; RU?: number; SA?: number; SE?: number; SG?: number; SK?: number; TH?: number; TR?: number; TW?: number; US?: number; VE?: number; ZA?: number; SI?: number; CV?: number; GH?: number; MU?: number; MZ?: number; UG?: number; IL?: number }; display_priority?: number; logo_path?: string; provider_name?: string; provider_id?: number }> }
export const WatchProvidersMovieListOutput = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    results: S.optional(S.Array(S.Struct({
      display_priorities: S.optional(S.Struct({
        CA: S.optional(S.Number),
        AE: S.optional(S.Number),
        AR: S.optional(S.Number),
        AT: S.optional(S.Number),
        AU: S.optional(S.Number),
        BE: S.optional(S.Number),
        BO: S.optional(S.Number),
        BR: S.optional(S.Number),
        BG: S.optional(S.Number),
        CH: S.optional(S.Number),
        CL: S.optional(S.Number),
        CO: S.optional(S.Number),
        CR: S.optional(S.Number),
        CZ: S.optional(S.Number),
        DE: S.optional(S.Number),
        DK: S.optional(S.Number),
        EC: S.optional(S.Number),
        EE: S.optional(S.Number),
        EG: S.optional(S.Number),
        ES: S.optional(S.Number),
        FI: S.optional(S.Number),
        FR: S.optional(S.Number),
        GB: S.optional(S.Number),
        GR: S.optional(S.Number),
        GT: S.optional(S.Number),
        HK: S.optional(S.Number),
        HN: S.optional(S.Number),
        HU: S.optional(S.Number),
        ID: S.optional(S.Number),
        IE: S.optional(S.Number),
        IN: S.optional(S.Number),
        IT: S.optional(S.Number),
        JP: S.optional(S.Number),
        LT: S.optional(S.Number),
        LV: S.optional(S.Number),
        MX: S.optional(S.Number),
        MY: S.optional(S.Number),
        NL: S.optional(S.Number),
        NO: S.optional(S.Number),
        NZ: S.optional(S.Number),
        PE: S.optional(S.Number),
        PH: S.optional(S.Number),
        PL: S.optional(S.Number),
        PT: S.optional(S.Number),
        PY: S.optional(S.Number),
        RU: S.optional(S.Number),
        SA: S.optional(S.Number),
        SE: S.optional(S.Number),
        SG: S.optional(S.Number),
        SK: S.optional(S.Number),
        TH: S.optional(S.Number),
        TR: S.optional(S.Number),
        TW: S.optional(S.Number),
        US: S.optional(S.Number),
        VE: S.optional(S.Number),
        ZA: S.optional(S.Number),
        SI: S.optional(S.Number),
        CV: S.optional(S.Number),
        GH: S.optional(S.Number),
        MU: S.optional(S.Number),
        MZ: S.optional(S.Number),
        UG: S.optional(S.Number),
        IL: S.optional(S.Number),
      })),
      display_priority: S.optional(S.Number),
      logo_path: S.optional(S.String),
      provider_name: S.optional(S.String),
      provider_id: S.optional(S.Number),
    }))),
  })
).annotate({ identifier: "WatchProvidersMovieListOutput" }) as unknown as S.Codec<WatchProvidersMovieListOutput>;

// The operation
/**
 * Movie Providers
 *
 * Get the list of streaming providers we have for movies.
 */
export type WatchProvidersMovieListError = TmdbOpError;
export const watchProvidersMovieList: API.OperationMethod<
  WatchProvidersMovieListInput,
  WatchProvidersMovieListOutput,
  WatchProvidersMovieListError,
  TmdbOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: WatchProvidersMovieListInput,
  output: WatchProvidersMovieListOutput,
  errors: [] as const,
  protocol: TmdbProtocol,
  retry: Retry.Retry,
}));

// Input Schema
export interface WatchProviderTvListInput { language?: string; watch_region?: string }
export const WatchProviderTvListInput = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    language: S.optional(S.String).pipe(T.Query("language")),
    watch_region: S.optional(S.String).pipe(T.Query("watch_region")),
  }).pipe(T.Http({ method: "GET", uri: "/3/watch/providers/tv", code: 200 }))
).annotate({ identifier: "WatchProviderTvListInput" }) as unknown as S.Codec<WatchProviderTvListInput>;

// Output Schema
export interface WatchProviderTvListOutput { results?: ReadonlyArray<{ display_priorities?: { CA?: number; AE?: number; AR?: number; AT?: number; AU?: number; BE?: number; BO?: number; BR?: number; BG?: number; CH?: number; CL?: number; CO?: number; CR?: number; CZ?: number; DE?: number; DK?: number; EC?: number; EE?: number; EG?: number; ES?: number; FI?: number; FR?: number; GB?: number; GR?: number; GT?: number; HK?: number; HN?: number; HU?: number; ID?: number; IE?: number; IN?: number; IT?: number; JP?: number; LT?: number; LV?: number; MX?: number; MY?: number; NL?: number; NO?: number; NZ?: number; PE?: number; PH?: number; PL?: number; PT?: number; PY?: number; RU?: number; SA?: number; SE?: number; SG?: number; SK?: number; TH?: number; TR?: number; TW?: number; US?: number; VE?: number; ZA?: number; SI?: number; CV?: number; GH?: number; MU?: number; MZ?: number; UG?: number; IL?: number }; display_priority?: number; logo_path?: string; provider_name?: string; provider_id?: number }> }
export const WatchProviderTvListOutput = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    results: S.optional(S.Array(S.Struct({
      display_priorities: S.optional(S.Struct({
        CA: S.optional(S.Number),
        AE: S.optional(S.Number),
        AR: S.optional(S.Number),
        AT: S.optional(S.Number),
        AU: S.optional(S.Number),
        BE: S.optional(S.Number),
        BO: S.optional(S.Number),
        BR: S.optional(S.Number),
        BG: S.optional(S.Number),
        CH: S.optional(S.Number),
        CL: S.optional(S.Number),
        CO: S.optional(S.Number),
        CR: S.optional(S.Number),
        CZ: S.optional(S.Number),
        DE: S.optional(S.Number),
        DK: S.optional(S.Number),
        EC: S.optional(S.Number),
        EE: S.optional(S.Number),
        EG: S.optional(S.Number),
        ES: S.optional(S.Number),
        FI: S.optional(S.Number),
        FR: S.optional(S.Number),
        GB: S.optional(S.Number),
        GR: S.optional(S.Number),
        GT: S.optional(S.Number),
        HK: S.optional(S.Number),
        HN: S.optional(S.Number),
        HU: S.optional(S.Number),
        ID: S.optional(S.Number),
        IE: S.optional(S.Number),
        IN: S.optional(S.Number),
        IT: S.optional(S.Number),
        JP: S.optional(S.Number),
        LT: S.optional(S.Number),
        LV: S.optional(S.Number),
        MX: S.optional(S.Number),
        MY: S.optional(S.Number),
        NL: S.optional(S.Number),
        NO: S.optional(S.Number),
        NZ: S.optional(S.Number),
        PE: S.optional(S.Number),
        PH: S.optional(S.Number),
        PL: S.optional(S.Number),
        PT: S.optional(S.Number),
        PY: S.optional(S.Number),
        RU: S.optional(S.Number),
        SA: S.optional(S.Number),
        SE: S.optional(S.Number),
        SG: S.optional(S.Number),
        SK: S.optional(S.Number),
        TH: S.optional(S.Number),
        TR: S.optional(S.Number),
        TW: S.optional(S.Number),
        US: S.optional(S.Number),
        VE: S.optional(S.Number),
        ZA: S.optional(S.Number),
        SI: S.optional(S.Number),
        CV: S.optional(S.Number),
        GH: S.optional(S.Number),
        MU: S.optional(S.Number),
        MZ: S.optional(S.Number),
        UG: S.optional(S.Number),
        IL: S.optional(S.Number),
      })),
      display_priority: S.optional(S.Number),
      logo_path: S.optional(S.String),
      provider_name: S.optional(S.String),
      provider_id: S.optional(S.Number),
    }))),
  })
).annotate({ identifier: "WatchProviderTvListOutput" }) as unknown as S.Codec<WatchProviderTvListOutput>;

// The operation
/**
 * TV Providers
 *
 * Get the list of streaming providers we have for TV shows.
 */
export type WatchProviderTvListError = TmdbOpError;
export const watchProviderTvList: API.OperationMethod<
  WatchProviderTvListInput,
  WatchProviderTvListOutput,
  WatchProviderTvListError,
  TmdbOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: WatchProviderTvListInput,
  output: WatchProviderTvListOutput,
  errors: [] as const,
  protocol: TmdbProtocol,
  retry: Retry.Retry,
}));
